[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "fec-py"
requires-python = ">=3.7"
version = "0.1.0"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.uv.workspace]
members = ["fec-py/fec-py"]
