import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import {
  COVER_TYPES,
  ITEMIZATION_TYPES,
  categoryCodeLabel,
  electionCodeLabel,
  entityTypeLabel,
  officeLabel,
  partyLabel,
  supportOpposeLabel,
} from "../dist/index.js";

const GENERATED = new URL("../js/generated/", import.meta.url);

test("ITEMIZATION_TYPES and COVER_TYPES list every union arm", () => {
  assert.equal(ITEMIZATION_TYPES.length, 27);
  for (const t of ["ScheduleA", "ScheduleA3L", "ScheduleC1", "TextRecord"]) {
    assert.ok(ITEMIZATION_TYPES.includes(t), t);
  }
  assert.equal(COVER_TYPES.length, 15);
  for (const t of ["Form3X", "Form99", "Form1M"]) assert.ok(COVER_TYPES.includes(t), t);
});

test("label functions trim, upper-case and return null for unknown codes", () => {
  assert.equal(entityTypeLabel("ind"), "Individual");
  assert.equal(entityTypeLabel(" PAC "), "Political Action Committee");
  assert.equal(entityTypeLabel("zz"), null);
  assert.equal(entityTypeLabel(null), null);
  assert.equal(entityTypeLabel(undefined), null);
  assert.equal(electionCodeLabel("P2026"), "Primary");
  assert.equal(electionCodeLabel("g2024"), "General");
  assert.equal(electionCodeLabel(""), null);
  assert.equal(officeLabel("h"), "House");
  assert.equal(partyLabel("DEM"), "Democratic Party");
  assert.equal(supportOpposeLabel("24E"), "Support");
  assert.equal(categoryCodeLabel("004"), "Advertising Expenses");
  assert.equal(categoryCodeLabel("4"), "Advertising Expenses");
  assert.equal(categoryCodeLabel("107"), "Fundraising Expenditures");
  assert.equal(categoryCodeLabel("4a"), null);
  assert.equal(categoryCodeLabel("toString"), null);
});

test("generated files: our header, no rustdoc links, no serde tags", () => {
  for (const f of readdirSync(GENERATED).filter((f) => f.endsWith(".ts"))) {
    const src = readFileSync(new URL(f, GENERATED), "utf8");
    assert.match(src, /^\/\/ Generated by scripts\/gen-types\.mjs/, f);
    assert.doesNotMatch(src, /\[`/, f);
    assert.doesNotMatch(src, /"family":|"form":/, f);
  }
});

test("keys.json has every struct in serde key order", () => {
  const keys = JSON.parse(readFileSync(new URL("keys.json", GENERATED), "utf8"));
  assert.deepEqual(keys.Entity, ["entity_type", "organization_name", "name", "address"]);
  assert.equal(keys.ScheduleA[0], "form_type");
  for (const t of [...ITEMIZATION_TYPES, ...COVER_TYPES]) assert.ok(keys[t], t);
});

test("the README lists every Itemization and Cover type", () => {
  const readme = readFileSync(new URL("../README.md", import.meta.url), "utf8").replace(/\r\n/g, "\n");
  const listed = (heading) => {
    const start = readme.indexOf(heading);
    const para = readme.slice(start, readme.indexOf("\n\n", start));
    return [...para.matchAll(/`(\w+)`/g)].map((m) => m[1]).filter((t) => /^[A-Z]/.test(t));
  };
  assert.deepEqual(listed("Every `Itemization` `type`").filter((t) => t !== "Itemization" && t !== "ITEMIZATION_TYPES"), [...ITEMIZATION_TYPES]);
  assert.deepEqual(listed("Every `Cover` `type`").filter((t) => t !== "Cover" && t !== "COVER_TYPES"), [...COVER_TYPES]);
});

test("js/ reaches the platform only through js/native.ts", () => {
  // A future browser build swaps js/native.ts for a wasm adapter, so no other
  // module may import the binding or node:* (plans/nodejs/06-wasm-spike.md W1).
  const dir = new URL("../js/", import.meta.url);
  for (const f of readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "native.ts")) {
    const src = readFileSync(new URL(f, dir), "utf8");
    assert.doesNotMatch(src, /^import .*from "(node:[^"]*|[^"]*native\/native[^"]*)"/m, f);
  }
  for (const f of readdirSync(GENERATED).filter((f) => f.endsWith(".ts"))) {
    const src = readFileSync(new URL(f, GENERATED), "utf8");
    // W5: generated code is pure (labels.ts included): no imports but its siblings.
    for (const m of src.matchAll(/^(?:import|export) .* from "([^"]+)";$/gm)) assert.match(m[1], /^\.\/\w+\.js$/, `${f}: ${m[1]}`);
  }
});
