# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib libfec, .registration = TRUE
NULL

#' Version of the bundled fec-parser crate
#'
#' Smoke test for the Rust bindings.
#'
#' @return A string such as `"0.1.0"`.
#' @export
#' @examples
#' fec_version_info()
fec_version_info <- function() .Call(wrap__fec_version_info)

# nolint end
