//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}

/// A mailing address as FEC forms collect it.
///
/// Read with a column prefix: `Address::from_prefixed(data, "")` reads
/// `street_1`, `street_2`, `city`, `state`, `zip_code`; with `"candidate_"` it
/// reads `candidate_street_1`, … .
pub type Address {
  Address(
    street_1: Option(String),
    street_2: Option(String),
    city: Option(String),
    state: Option(String),
    zip_code: Option(String),
  )
}

/// A person's name, split the way FEC forms collect it.
///
/// Read with a column prefix: `PersonName::from_prefixed(data, "treasurer_")`
/// reads `treasurer_last_name`, `treasurer_first_name`, `treasurer_middle_name`,
/// `treasurer_prefix` and `treasurer_suffix`.
pub type PersonName {
  PersonName(
    first_name: String,
    last_name: String,
    middle_name: Option(String),
    prefix: Option(String),
    suffix: Option(String),
  )
}

/// One line of a two-column summary page: Column A and Column B.
///
/// What the columns mean depends on the form. On Forms 3 and 3P Column A is
/// "Total This Period" and Column B "Election Cycle-to-Date"; on Form 3X
/// Column B is "Calendar Year-to-Date". Each form's struct documents its own.
pub type DetailedSummaryRow {
  DetailedSummaryRow(column_a: Float, column_b: Float)
}
