//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form3`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{
  type Address, type DetailedSummaryRow, type PersonName,
}

/// FEC Form 3, "Report of Receipts and Disbursements for an Authorized
/// Committee": the periodic report of a House or Senate candidate's principal
/// campaign committee.
///
/// **Who files.** The principal campaign committee designated by a candidate
/// for the House of Representatives or Senate; presidential committees use
/// Form 3P and committees not authorized by a candidate use Form 3X
/// ([fecfrm3i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=2)).
///
/// **Layout.** Page 1 identifies the committee, the type of report and the
/// coverage period; page 2 is the Summary Page; pages 3–4 the Detailed Summary
/// Page ([fecfrm3i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=1)).
/// The `F3` record carries all four pages in one row (FEC format workbook v8.4,
/// sheet `F3`, fields 1–93). Page 1 is the top-level fields of this struct;
/// page 2 is `Form3::summary`; pages 3–4 are `Form3::detailed_summary`.
///
/// **Columns.** On the Summary and Detailed Summary pages, Column A
/// (`DetailedSummaryRow::column_a`) is "Total This Period" and Column B
/// (`DetailedSummaryRow::column_b`) is "Election Cycle-to-Date", not calendar
/// year-to-date ([fecfrm3.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=2),
/// [p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=3),
/// [p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=4)).
/// The election cycle begins the day after the previous general election for
/// the seat and ends on the day of the next one
/// ([fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
/// Lines 8–10 and 23–27 have a single amount, read from the record's Column A
/// block (FEC format workbook v8.4, sheet `F3`, fields 30–32 and 58–62).
///
/// **Derived lines.** The Summary Page is carried from the Detailed Summary
/// Page: 6(a) is 11(e), 6(b) is 20(d), 7(a) is 17, 7(b) is 14, 8 is 27
/// ([fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
/// Over 15,500 v8.x filings these identities hold on ≥ 99.7% of records; see
/// `wiki/covers/F3.md` for the full table.
///
/// **Post-general reports.** For the report covering the general election the
/// paper form substitutes a three-column Post-Election Detailed Summary Page
/// ([fecfrm3posti.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3posti.pdf#page=1));
/// the `F3` record has no Column C, and the FEC sources do not say which paper
/// column the record's Column B holds on such a report.
pub type Form3 {
  Form3(
    /// Form type as filed, e.g. `F3N`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F3`, field 1).
    /// `N` (new) or `A` (amended) match Line 3 "Is this report New (N) or
    /// Amended (A)"
    /// ([fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1));
    /// the workbook also lists `T` without defining it.
    form_type: String,
    /// Line 2, the committee's FEC identification number
    /// (`filer_committee_id_number`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    filer_committee_id: String,
    /// Line 1, the committee's full name (`committee_name`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    committee_name: String,
    /// Line 1, the committee's mailing address (`street_1`, `street_2`, `city`,
    /// `state`, `zip_code`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    address: Address,
    /// The "Check if different than previously reported (ACC)" box beside the
    /// address (`change_of_address`, `X` = yes;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1);
    /// FEC format workbook v8.4, sheet `F3`, field 4).
    change_of_address: Bool,
    /// The "STATE" box printed beside Line 2 on page 1 (`election_state`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1);
    /// FEC format workbook v8.4, sheet `F3`, field 10, "ELECTION STATE"). The
    /// instructions do not describe this box.
    election_state: Option(String),
    /// The "DISTRICT" box printed beside Line 2 on page 1, `01`–`99`
    /// (`election_district`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1);
    /// FEC format workbook v8.4, sheet `F3`, field 11, "ELECTION DISTRICT").
    /// The instructions do not describe this box.
    election_district: Option(String),
    /// Line 4, type of report: one of the codes printed beside the page-1
    /// checkboxes, e.g. `Q1`, `YE`, `12P`, `30G`, `TER` (`report_code`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    /// See `Form3::report_code_label`.
    report_code: Option(String),
    /// For a 12-day pre-election or 30-day post-election report, the type of
    /// election (primary, general, convention, special or runoff) chosen on
    /// Line 4 ([fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)),
    /// coded as a letter plus the election year, e.g. `P2026` (`election_code`;
    /// FEC format workbook v8.4, sheet `F3`, field 13). See
    /// `Form3::election_code_label`.
    election_code: Option(String),
    /// Line 4, "Election on": the date of the election a 12-day pre- or 30-day
    /// post-election report is for (`election_date`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    election_date: Option(calendar.Date),
    /// Line 4, "in the State of": the state holding that election
    /// (`state_of_election`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    state_of_election: Option(String),
    /// Line 5, first day of the covering period (`coverage_from_date`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    coverage_from_date: Option(calendar.Date),
    /// Line 5, last day of the covering period (`coverage_through_date`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    /// All activity since the last report's ending date must be included
    /// ([fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    coverage_through_date: Option(calendar.Date),
    /// "Type or Print Name of Treasurer" (`treasurer_*`; the single
    /// caret-delimited `treasurer_name` of v1–v5.x formats is split into parts;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    treasurer: PersonName,
    /// Date the treasurer signed the certification (`date_signed`;
    /// [fecfrm3.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=1)).
    date_signed: Option(calendar.Date),
    /// Page 2, the Summary Page (Lines 6–10).
    summary: Form3Summary,
    /// Pages 3–4, the Detailed Summary Page (Lines 11–27).
    detailed_summary: Form3DetailedSummary,
  )
}

/// Form 3 page 2, the Summary Page
/// ([fecfrm3.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=2)).
///
/// Lines 6 and 7 have Column A ("This Period") and Column B ("Election
/// Cycle-to-Date"); Lines 8–10 have one amount. Every line is carried from the
/// Detailed Summary Page or the debt schedules
/// ([fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
pub type Form3Summary {
  Form3Summary(
    /// Line 6(a), total contributions (other than loans), carried from Line
    /// 11(e) (`col_a_total_contributions_no_loans`,
    /// `col_b_total_contributions_no_loans`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line6a_total_contributions: DetailedSummaryRow,
    /// Line 6(b), total contribution refunds, carried from Line 20(d)
    /// (`col_a_total_contributions_refunds`, `col_b_total_contributions_refunds`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line6b_total_contribution_refunds: DetailedSummaryRow,
    /// Line 6(c), net contributions (other than loans) = 6(a) − 6(b)
    /// (`col_a_net_contributions`, `col_b_net_contributions`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line6c_net_contributions: DetailedSummaryRow,
    /// Line 7(a), total operating expenditures, carried from Line 17
    /// (`col_a_total_operating_expenditures`,
    /// `col_b_total_operating_expenditures`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line7a_total_operating_expenditures: DetailedSummaryRow,
    /// Line 7(b), total offsets to operating expenditures, carried from Line 14
    /// (`col_a_total_offset_to_operating_expenditures`,
    /// `col_b_total_offset_to_operating_expenditures`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line7b_total_offsets_to_operating_expenditures: DetailedSummaryRow,
    /// Line 7(c), net operating expenditures = 7(a) − 7(b)
    /// (`col_a_net_operating_expenditures`, `col_b_net_operating_expenditures`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line7c_net_operating_expenditures: DetailedSummaryRow,
    /// Line 8, cash on hand at close of reporting period, carried from Line 27
    /// (`col_a_cash_on_hand_close_of_period`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line8_cash_on_hand_close_of_period: Float,
    /// Line 9, debts and obligations owed TO the committee, from Schedule C or
    /// D (`col_a_debts_to`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line9_debts_owed_to_committee: Float,
    /// Line 10, debts and obligations owed BY the committee, from Schedule C or
    /// D (`col_a_debts_by`;
    /// [fecfrm3i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=3)).
    line10_debts_owed_by_committee: Float,
  )
}

/// Form 3 pages 3–4, the Detailed Summary Page
/// ([fecfrm3.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=3),
/// [p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=4)).
pub type Form3DetailedSummary {
  Form3DetailedSummary(
    /// Part I, Receipts (Lines 11–16).
    receipts: Form3DetailedSummaryReceipts,
    /// Part II, Disbursements (Lines 17–22).
    disbursements: Form3DetailedSummaryDisbursements,
    /// Part III, Cash Summary (Lines 23–27).
    cash_summary: Form3CashSummary,
  )
}

/// Form 3 page 3, Detailed Summary Page Part I, Receipts (Lines 11–16)
/// ([fecfrm3.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=3)).
///
/// Column A is "Total This Period", Column B "Election Cycle-to-Date". Each
/// schedule's total is added to the unitemized amount for its category before
/// being entered here, so summing Schedule A rows will not generally reproduce
/// these lines ([fecfrm3i.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=6)).
pub type Form3DetailedSummaryReceipts {
  Form3DetailedSummaryReceipts(
    /// Line 11(a)(i), contributions from individuals/persons other than
    /// political committees that must be itemized on Schedule A (over $200 in
    /// the election cycle) (`col_a_individual_contributions_itemized`,
    /// `col_b_individual_contributions_itemized`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11a_i_contributions_from_individuals_itemized: DetailedSummaryRow,
    /// Line 11(a)(ii), contributions from individuals not required to be
    /// itemized (`col_a_individual_contributions_unitemized`,
    /// `col_b_individual_contributions_unitemized`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11a_ii_contributions_from_individuals_unitemized: DetailedSummaryRow,
    /// Line 11(a)(iii), total contributions from individuals = 11(a)(i) +
    /// 11(a)(ii) (`col_a_total_individual_contributions`,
    /// `col_b_total_individual_contributions`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11a_iii_contributions_from_individuals_total: DetailedSummaryRow,
    /// Line 11(b), contributions (other than loans) from political party
    /// committees, all itemized on Schedule A
    /// (`col_a_political_party_contributions`,
    /// `col_b_political_party_contributions`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11b_political_party_committees: DetailedSummaryRow,
    /// Line 11(c), contributions (other than loans) from other political
    /// committees such as PACs, all itemized on Schedule A
    /// (`col_a_pac_contributions`, `col_b_pac_contributions`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11c_other_political_committees_pacs: DetailedSummaryRow,
    /// Line 11(d), contributions (other than loans) from the candidate
    /// (`col_a_candidate_contributions`, `col_b_candidate_contributions`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11d_the_candidate: DetailedSummaryRow,
    /// Line 11(e), total contributions (other than loans) =
    /// 11(a)(iii) + 11(b) + 11(c) + 11(d) (`col_a_total_contributions`,
    /// `col_b_total_contributions`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line11e_total_contributions: DetailedSummaryRow,
    /// Line 12, transfers from other authorized committees of the same
    /// candidate, including loans and loan repayments from them
    /// (`col_a_transfers_from_authorized`, `col_b_transfers_from_authorized`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line12_transfers_from_authorized: DetailedSummaryRow,
    /// Line 13(a), loans made or guaranteed by the candidate
    /// (`col_a_candidate_loans`, `col_b_candidate_loans`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line13a_loans_from_candidate: DetailedSummaryRow,
    /// Line 13(b), all other loans (`col_a_other_loans`, `col_b_other_loans`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line13b_other_loans: DetailedSummaryRow,
    /// Line 13(c), total loans = 13(a) + 13(b) (`col_a_total_loans`,
    /// `col_b_total_loans`;
    /// [fecfrm3.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=3)).
    line13c_total_loans: DetailedSummaryRow,
    /// Line 14, offsets to operating expenditures (refunds, rebates, returns of
    /// deposits) (`col_a_offset_to_operating_expenditures`,
    /// `col_b_offset_to_operating_expenditures`;
    /// [fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4)).
    line14_offset_to_operating_expenditures: DetailedSummaryRow,
    /// Line 15, other receipts (dividends, interest, etc.)
    /// (`col_a_other_receipts`, `col_b_other_receipts`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line15_other_receipts: DetailedSummaryRow,
    /// Line 16, total receipts = 11(e) + 12 + 13(c) + 14 + 15
    /// (`col_a_total_receipts`, `col_b_total_receipts`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line16_total_receipts: DetailedSummaryRow,
  )
}

/// Form 3 page 4, Detailed Summary Page Part II, Disbursements (Lines 17–22)
/// ([fecfrm3.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=4)).
///
/// Column A is "Total This Period", Column B "Election Cycle-to-Date".
pub type Form3DetailedSummaryDisbursements {
  Form3DetailedSummaryDisbursements(
    /// Line 17, operating expenditures, e.g. advertising, salaries, travel,
    /// rent, telephones (`col_a_operating_expenditures`,
    /// `col_b_operating_expenditures`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line17_operating_expenditures: DetailedSummaryRow,
    /// Line 18, transfers to other authorized committees of the same candidate
    /// (`col_a_transfers_to_authorized`, `col_b_transfers_to_authorized`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line18_transfers_to_authorized: DetailedSummaryRow,
    /// Line 19(a), repayments of loans made or guaranteed by the candidate
    /// (`col_a_candidate_loan_repayments`, `col_b_candidate_loan_repayments`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line19a_candidate_loan_repayments: DetailedSummaryRow,
    /// Line 19(b), repayments of all other loans
    /// (`col_a_other_loan_repayments`, `col_b_other_loan_repayments`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line19b_other_loan_repayments: DetailedSummaryRow,
    /// Line 19(c), total loan repayments = 19(a) + 19(b)
    /// (`col_a_total_loan_repayments`, `col_b_total_loan_repayments`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line19c_total_loan_repayments: DetailedSummaryRow,
    /// Line 20(a), contribution refunds to individuals/persons other than
    /// political committees (`col_a_refunds_to_individuals`,
    /// `col_b_refunds_to_individuals`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line20a_refunds_to_individuals: DetailedSummaryRow,
    /// Line 20(b), contribution refunds to political party committees
    /// (`col_a_refunds_to_party_committees`, `col_b_refunds_to_party_committees`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line20b_refunds_to_party_committees: DetailedSummaryRow,
    /// Line 20(c), contribution refunds to other political committees such as
    /// PACs (`col_a_refunds_to_other_committees`,
    /// `col_b_refunds_to_other_committees`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line20c_refunds_to_other_committees: DetailedSummaryRow,
    /// Line 20(d), total contribution refunds = 20(a) + 20(b) + 20(c)
    /// (`col_a_total_refunds`, `col_b_total_refunds`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line20d_total_refunds: DetailedSummaryRow,
    /// Line 21, other disbursements (`col_a_other_disbursements`,
    /// `col_b_other_disbursements`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line21_other_disbursements: DetailedSummaryRow,
    /// Line 22, total disbursements = 17 + 18 + 19(c) + 20(d) + 21
    /// (`col_a_total_disbursements`, `col_b_total_disbursements`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line22_total_disbursements: DetailedSummaryRow,
  )
}

/// Form 3 page 4, Detailed Summary Page Part III, Cash Summary (Lines 23–27),
/// single amounts for this period
/// ([fecfrm3.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3.pdf#page=4)).
pub type Form3CashSummary {
  Form3CashSummary(
    /// Line 23, cash on hand at beginning of reporting period: currency, bank
    /// balances, traveler's checks, CDs, treasury bills and other investments
    /// valued at cost (`col_a_cash_beginning_reporting_period`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line23_cash_on_hand_beginning: Float,
    /// Line 24, total receipts this period, carried from Line 16 Column A
    /// (`col_a_total_receipts_period`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line24_total_receipts: Float,
    /// Line 25, subtotal = 23 + 24 (`col_a_subtotals`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line25_subtotal: Float,
    /// Line 26, total disbursements this period, carried from Line 22 Column A
    /// (`col_a_total_disbursements_period`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line26_total_disbursements: Float,
    /// Line 27, cash on hand at close of reporting period = 25 − 26
    /// (`col_a_cash_on_hand_close`;
    /// [fecfrm3i.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=5)).
    line27_cash_on_hand_close: Float,
  )
}
