//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form4`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{
  type Address, type DetailedSummaryRow, type PersonName,
}

/// FEC Form 4, "Report of Receipts and Disbursements for a Committee or
/// Organization Supporting a Nominating Convention" — the `F4N` / `F4A` /
/// `F4T` cover record.
///
/// **Who files.** Convention committees established by a national party
/// committee; host committees and other organizations representing a State,
/// municipality or other political subdivision in dealing with national party
/// officials on a presidential nominating convention; and any other
/// organization that makes convention arrangements for a political party
/// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
///
/// **When.** Quarterly reports, a post-convention report (report code `60D`)
/// and, for a host committee, a final report once its convention activity has
/// ceased
/// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
///
/// **Pages.** Page 1 is the Summary Page: Section A, the cash summary (Lines
/// 6–10), and Section B, expenditures subject to limitation (Lines 11–12(c))
/// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
/// Page 2 is the Detailed Summary Page: receipts (Lines 13–20) and
/// disbursements (Lines 21–25)
/// ([fecfrm4.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=2)).
/// They are `Form4::summary` and `Form4::detailed_summary`.
///
/// **Columns.** In every `DetailedSummaryRow` on this form, **Column A is
/// "This Period"** and **Column B is "Calendar Year-to-Date"**
/// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1),
/// [p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=2));
/// Column B is the previous report's year-to-date figure plus this period's
/// Column A
/// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
/// Column B exists only for subtotals and totals: the (a)/(b) sub-lines, Line
/// 6(b) and Lines 9–10 are Column A only, and Lines 6(a) and 12(c) are Column B
/// only (FEC format workbook v8.4, sheet `F4`, fields 20–83). Those lines are
/// plain `f64` fields here.
///
/// **Versions.** v6.1–v8.5 share one layout. The legacy v3/v5 layouts lack the
/// split treasurer name (one caret-delimited `treasurer_name` column, split
/// into parts) and name Lines 20/25 without the
/// `_TODO_DUP` suffix, so the Line 6(c)/7 and 20/25 columns collide and both
/// read the Line 20/25 value, which the instructions require to be equal
/// anyway.
pub type Form4 {
  Form4(
    /// Form type as filed, e.g. `F4N`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F4`, field 1).
    form_type: String,
    /// Line 1(a), name of the committee (`committee_name`)
    /// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
    committee_name: String,
    /// Line 2, FEC identification number (`filer_committee_id_number`)
    /// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
    filer_committee_id: String,
    /// Line 1(b)–(c), mailing address (`street_1`, `street_2`, `city`,
    /// `state`, `zip_code`)
    /// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
    address: Address,
    /// Line 3, type of committee/organization (`committee_type`): `A`, `H` or
    /// `O`. See `Form4::committee_type_label`.
    committee_type: Option(String),
    /// Line 3 "Other (specify)" text (`committee_type_description`)
    /// (FEC format workbook v8.4, sheet `F4`, field 10).
    committee_type_description: Option(String),
    /// Line 4, type of report (`report_code`). See
    /// `Form4::report_code_label`.
    report_code: Option(String),
    /// Line 5, first day of the covering period (`coverage_from_date`)
    /// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
    coverage_from_date: Option(calendar.Date),
    /// Line 5, last day of the covering period (`coverage_through_date`).
    coverage_through_date: Option(calendar.Date),
    /// The treasurer who signed the certification (`treasurer_last_name`,
    /// `treasurer_first_name`, `treasurer_middle_name`, `treasurer_prefix`,
    /// `treasurer_suffix`; legacy caret-delimited `treasurer_name` split into
    /// parts)
    /// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
    treasurer: PersonName,
    /// Date signed (`date_signed`).
    date_signed: Option(calendar.Date),
    /// Page 1, Summary Page (Lines 6–12(c)).
    summary: Form4Summary,
    /// Page 2, Detailed Summary Page (Lines 13–25).
    detailed_summary: Form4DetailedSummary,
  )
}

/// Page 1, Summary Page
/// ([fecfrm4.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=1)).
/// Column A = This Period, Column B = Calendar Year-to-Date.
pub type Form4Summary {
  Form4Summary(
    /// Line 6(a), cash on hand January 1 of the year — Column B only
    /// (`col_b_cash_on_hand_beginning_year`)
    /// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
    line6a_cash_on_hand_jan_1: Float,
    /// Line 6(a), the year printed after "January 1, 20__"
    /// (`col_b_beginning_year`) (FEC format workbook v8.4, sheet `F4`,
    /// field 61).
    line6a_year: Option(Int),
    /// Line 6(b), cash on hand at the beginning of the reporting period —
    /// Column A only (`col_a_cash_on_hand_beginning_reporting_period`)
    /// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
    line6b_cash_on_hand_beginning_period: Float,
    /// Line 6(c), total receipts, from Line 20 (`col_a_total_receipts`,
    /// `col_b_total_receipts`)
    /// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
    line6c_total_receipts: DetailedSummaryRow,
    /// Line 6(d), subtotal: 6(b) + 6(c) for Column A, 6(a) + 6(c) for Column
    /// B (`col_a_subtotal`, `col_b_subtotal`)
    /// ([fecfrm4i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=1)).
    line6d_subtotal: DetailedSummaryRow,
    /// Line 7, total disbursements, from Line 25
    /// (`col_a_total_disbursements`, `col_b_total_disbursements`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line7_total_disbursements: DetailedSummaryRow,
    /// Line 8, cash on hand at close of the reporting period: 6(d) − 7, "which
    /// should be the same for both columns"
    /// (`col_a_cash_on_hand_close_of_period`, `col_b_cash_on_hand_close_of_period`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line8_cash_on_hand_close_of_period: DetailedSummaryRow,
    /// Line 9, debts and obligations owed TO the committee, from Schedule C
    /// or D — Column A only (`col_a_debts_to`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line9_debts_owed_to_committee: Float,
    /// Line 10, debts and obligations owed BY the committee, from Schedule C
    /// or D — Column A only (`col_a_debts_by`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line10_debts_owed_by_committee: Float,
    /// Line 11, convention expenditures, from Line 21(c)
    /// (`col_a_convention_expenditures`, `col_b_convention_expenditures`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line11_convention_expenditures: DetailedSummaryRow,
    /// Line 12, refunds, rebates and returns of deposits relating to
    /// convention expenditures, from Line 17(c) (`col_a_convention_refunds`,
    /// `col_b_convention_refunds`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line12_convention_refunds: DetailedSummaryRow,
    /// Line 12(a), expenditures subject to limitation: 11 − 12
    /// (`col_a_expenditures_subject_to_limits`,
    /// `col_b_expenditures_subject_to_limits`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line12a_expenditures_subject_to_limitation: DetailedSummaryRow,
    /// Line 12(b), expenditures from prior years subject to limitation
    /// (`col_a_prior_expenditures_subject_to_limits`,
    /// `col_b_prior_expendiutres_subject_to_limits` — sic)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line12b_prior_years_expenditures_subject_to_limitation: DetailedSummaryRow,
    /// Line 12(c), total expenditures subject to limitation: 12(a) + 12(b) —
    /// Column B only (`col_b_total_expenditures_subject_to_limits`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2);
    /// FEC format workbook v8.4, sheet `F4`, field 70).
    line12c_total_expenditures_subject_to_limitation: Float,
  )
}

/// Page 2, Detailed Summary Page
/// ([fecfrm4.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=2)).
pub type Form4DetailedSummary {
  Form4DetailedSummary(
    /// "RECEIPTS", Lines 13–20.
    receipts: Form4Receipts,
    /// "DISBURSEMENTS", Lines 21–25.
    disbursements: Form4Disbursements,
  )
}

/// Detailed Summary Page, receipts (Lines 13–20)
/// ([fecfrm4i.pdf p2–3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
pub type Form4Receipts {
  Form4Receipts(
    /// Line 13, federal funds: "receipts from the Presidential Election
    /// Campaign Fund (US Treasury)" (`col_a_federal_funds`,
    /// `col_b_federal_funds`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line13_federal_funds: DetailedSummaryRow,
    /// Line 14, contributions to defray convention expenses
    /// (`col_a_contributions_itemized`, `col_a_contributions_unitemized`,
    /// `col_a_contributions_subtotal`, `col_b_contributions_subtotal`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line14_contributions: Form4ItemizedLine,
    /// Line 15, transfers from affiliated committees, including loans and
    /// loan repayments received from them (`col_a_transfers_from_affiliated`,
    /// `col_b_transfers_from_affiliated`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line15_transfers_from_affiliated_committees: DetailedSummaryRow,
    /// Line 16, loans (a) and loan repayments (b) received, other than from
    /// affiliated committees (`col_a_loans_received`,
    /// `col_a_loan_repayments_received`, `col_a_loan_receipts_subtotal`,
    /// `col_b_loan_receipts_subtotal`)
    /// ([fecfrm4i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line16_loans_received: Form4LoanLine,
    /// Line 17, refunds, rebates and returns of deposits relating to
    /// convention expenditures (`col_a_convention_refunds_itemized`,
    /// `col_a_convention_refunds_unitemized`,
    /// `col_a_convention_refunds_subtotal`,
    /// `col_b_convention_refunds_subtotal`)
    /// ([fecfrm4i.pdf p2–3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=2)).
    line17_convention_refunds: Form4ItemizedLine,
    /// Line 18, other refunds, rebates and returns of deposits — those
    /// relating to "Other Disbursements" on Line 24
    /// (`col_a_other_refunds_itemized`, `col_a_other_refunds_unitemized`,
    /// `col_a_other_refunds_subtotal`, `col_b_other_refunds_subtotal`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line18_other_refunds: Form4ItemizedLine,
    /// Line 19, other income. "For convention committees this would include
    /// interest and dividends. For host committees other income would include
    /// contributions received to promote the city and its commerce"
    /// (`col_a_other_income_itemized`, `col_a_other_income_unitemized`,
    /// `col_a_other_income_subtotal`, `col_b_other_income_subtotal`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line19_other_income: Form4ItemizedLine,
    /// Line 20, total receipts: 13 + 14(c) + 15 + 16(c) + 17(c) + 18(c) +
    /// 19(c) (`col_a_total_receipts_TODO_DUP`, `col_b_total_receipts_TODO_DUP`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line20_total_receipts: DetailedSummaryRow,
  )
}

/// A detailed-summary category split into (a) itemized, (b) unitemized and
/// (c) subtotal, as on Form 4 Lines 14, 17, 18, 19, 21 and 24
/// ([fecfrm4.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=2)).
/// The (a)/(b) boxes are Column A (This Period) only; the subtotal has both
/// columns.
pub type Form4ItemizedLine {
  Form4ItemizedLine(
    /// (a) itemized amount, This Period.
    itemized: Float,
    /// (b) unitemized amount, This Period.
    unitemized: Float,
    /// (c) subtotal: (a) + (b) in Column A; Calendar Year-to-Date in Column B.
    subtotal: DetailedSummaryRow,
  )
}

/// Loans and loan repayments, Form 4 Lines 16 (received) and 23 (made):
/// (a) loans, (b) loan repayments, (c) subtotal
/// ([fecfrm4.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4.pdf#page=2)).
pub type Form4LoanLine {
  Form4LoanLine(
    /// (a) loans received / made, This Period.
    loans: Float,
    /// (b) loan repayments received / made, This Period.
    loan_repayments: Float,
    /// (c) subtotal: (a) + (b) in Column A; Calendar Year-to-Date in Column B.
    subtotal: DetailedSummaryRow,
  )
}

/// Detailed Summary Page, disbursements (Lines 21–25)
/// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
pub type Form4Disbursements {
  Form4Disbursements(
    /// Line 21, convention expenditures: "disbursements made to defray
    /// convention expenses" (`col_a_convention_expenses_itemized`,
    /// `col_a_convention_expenses_unitemized`,
    /// `col_a_convention_expenses_subtotal`,
    /// `col_b_convention_expenses_subtotal`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line21_convention_expenditures: Form4ItemizedLine,
    /// Line 22, transfers to affiliated committees, including loans and loan
    /// repayments made to them (`col_a_transfers_to_affiliated`,
    /// `col_b_transfers_to_affiliated`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line22_transfers_to_affiliated_committees: DetailedSummaryRow,
    /// Line 23, loans made (a) and loan repayments made (b), excluding
    /// transfers on Line 22 (`col_a_loans_made`, `col_a_loan_repayments_made`,
    /// `col_a_loan_disbursements_subtotal`, `col_b_loan_disbursements_subtotal`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line23_loans_made: Form4LoanLine,
    /// Line 24, other disbursements (`col_a_other_disbursements_itemized`,
    /// `col_a_other_disbursements_unitemized`,
    /// `col_a_other_disbursements_subtotal`,
    /// `col_b_other_disbursements_subtotal`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line24_other_disbursements: Form4ItemizedLine,
    /// Line 25, total disbursements: 21(c) + 22 + 23(c) + 24(c)
    /// (`col_a_total_disbursements_TODO_DUP`,
    /// `col_b_total_disbursements_TODO_DUP`)
    /// ([fecfrm4i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm4i.pdf#page=3)).
    line25_total_disbursements: DetailedSummaryRow,
  )
}
