//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form9`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address, type PersonName}

/// "FEC FORM 9 - 24 HOUR NOTICE OF DISBURSEMENTS/OBLIGATIONS FOR
/// ELECTIONEERING COMMUNICATIONS" (form REV. 01/2018,
/// [fecfrm9.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=1)).
/// Form types `F9N` (new) and `F9A` (amendment).
///
/// **What it reports.** An electioneering communication is "any broadcast,
/// cable or satellite communication that (1) refers to a clearly identified
/// candidate; (2) is publicly distributed; (3) is distributed within 60 days
/// prior to a general election or 30 days prior to a primary election; and
/// (4) can be received by 50,000 or more people" in the candidate's district
/// or state. "Disbursements" "includes actual disbursements and the execution
/// of contracts creating an obligation to make disbursements" (instructions
/// revised 01/2018,
/// [fecfrm9i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=1)).
///
/// **Who files, when.** "Every person that makes disbursements for
/// electioneering communications aggregating in excess of $10,000 during a
/// calendar year", by 11:59 p.m. Eastern of the day after the communication is
/// first publicly distributed, and again each time later disbursements
/// aggregate in excess of $10,000
/// ([fecfrm9i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=1)).
/// A "person" may be "an individual, unincorporated organization, corporation
/// or labor organization"; political committees report on Form 3X instead
/// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
///
/// **Line numbers.** The 01/2018 paper form prints the totals as Lines 10
/// and 11; the v8.4 workbook labels the same fields "9." and "10." (FEC
/// format workbook v8.4, sheet F9, fields 38-39). Docs here use the paper
/// numbering.
///
/// # Versions
///
/// v8.3–8.5 is the layout documented here. v6.2–8.2 lack
/// `original_amendment_date`. v6.1 and v5.x have `qualified_non_profit` in
/// place of `filer_code`/`filer_code_description`; v5.x has no individual name
/// columns, and gives the custodian and person completing the form as single
/// caret-delimited names in the `custodian_last_name` and
/// `person_completing_last_name` columns, which are split into parts (FEC
/// format workbook v5.2, sheet F9).
///
/// The test fixture is a real `F9A` (FEC-2015422, v8.5); no `F9N` was
/// available locally.
pub type Form9 {
  Form9(
    /// Form type as filed, e.g. `F9N`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F9`, field 1).
    form_type: String,
    /// Line 3, the filer's FEC identification number ("First time
    /// filers—leave this line blank",
    /// [fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Column `filer_committee_id_number` (FEC format workbook v8.4, sheet F9,
    /// field 2).
    filer_committee_id: String,
    /// Electronic-format entity code, one of `COM, IND, ORG, PAC, PTY` (no
    /// box on the paper form; the workbook gives no descriptions). Column
    /// `entity_type` (FEC format workbook v8.4, sheet F9, field 3).
    entity_type: Option(String),
    /// Line 1(a), name of the organization or corporation making the
    /// disbursements. Column `organization_name` (FEC format workbook v8.4,
    /// sheet F9, field 4).
    organization_name: Option(String),
    /// Line 1(a), name of the individual making the disbursements. Columns
    /// `individual_last_name`, `individual_first_name`,
    /// `individual_middle_name`, `individual_prefix`, `individual_suffix` (FEC
    /// format workbook v8.4, sheet F9, fields 5-9).
    individual: PersonName,
    /// Line 1(b) "check if different than previously reported" (`X` = yes).
    /// Column `change_of_address` (FEC format workbook v8.4, sheet F9,
    /// field 10).
    change_of_address: Bool,
    /// Lines 1(b)-(c), the filer's address. Columns `street_1`, `street_2`,
    /// `city`, `state`, `zip_code` (FEC format workbook v8.4, sheet F9,
    /// fields 11-15).
    address: Address,
    /// Line 2, employer, "If Entity is an Individual". Column
    /// `individual_employer` (FEC format workbook v8.4, sheet F9, field 16).
    individual_employer: Option(String),
    /// Line 2, occupation, "If Entity is an Individual". Column
    /// `individual_occupation` (FEC format workbook v8.4, sheet F9, field 17).
    individual_occupation: Option(String),
    /// Line 5, on an amendment the date of the report it amends ("Use date of
    /// original report or of most recent amendment"). Column
    /// `original_amendment_date` (FEC format workbook v8.4, sheet F9,
    /// field 18). v8.3+ only.
    original_amendment_date: Option(calendar.Date),
    /// Line 4, covered period start. These dates "should begin with the date
    /// of the first related disbursement and end with the date of public
    /// distribution"
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Column `coverage_from_date` (FEC format workbook v8.4, sheet F9,
    /// field 19).
    coverage_from_date: Option(calendar.Date),
    /// Line 4, covered period end. Column `coverage_through_date` (FEC format
    /// workbook v8.4, sheet F9, field 20).
    coverage_through_date: Option(calendar.Date),
    /// Line 6(a), date of public distribution: the date the communication
    /// was first publicly distributed, or for a later notice about the same
    /// communication the date it was distributed again
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Column `date_public_distribution` (FEC format workbook v8.4, sheet F9,
    /// field 21).
    date_public_distribution: Option(calendar.Date),
    /// Line 6(b), the communication's title "as named by the media vendor or
    /// producer"
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Column `communication_title` (FEC format workbook v8.4, sheet F9,
    /// field 22).
    communication_title: Option(String),
    /// Line 7, "THE FILER IS": one of `IND`, `UNO`, `QNC`, `CLQ`, `OTH`.
    /// Column `filer_code` (FEC format workbook v8.4, sheet F9, field 23). See
    /// `Form9::filer_code_label`. v6.2+ only.
    filer_code: Option(String),
    /// Line 7(d) "Other, specify:", required when the filer code is `OTH`.
    /// Column `filer_code_description` (FEC format workbook v8.4, sheet F9,
    /// field 24).
    filer_code_description: Option(String),
    /// v6.1/v5.x only: "QUALIFIED NON-PROFIT", `Y` or `N` (FEC format
    /// workbook v5.2, sheet F9, field 16). Column `qualified_non_profit`.
    qualified_nonprofit: Option(String),
    /// Line 8, "WERE THE DISBURSEMENTS MADE EXCLUSIVELY FROM DONATIONS TO A
    /// SEGREGATED BANK ACCOUNT?": `Y` or `N`. The answer changes which donors
    /// must be itemized on Schedule 9-A
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Column `segregated_bank_account` (FEC format workbook v8.4, sheet F9,
    /// field 25, `Y=YES, N=NO`). See `Form9::used_segregated_bank_account`.
    segregated_bank_account: Option(String),
    /// Line 9, custodian of records: "the individual who controls the books
    /// and records that support this filing"
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    custodian: Form9Custodian,
    /// Line 10, total donations this statement: "the sum total of donations
    /// itemized on Schedule 9A", or zero if none required itemization
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Workbook rule "= Sum of F92 Donations". Column `total_donations` (FEC
    /// format workbook v8.4, sheet F9, field 38, labelled line 9 there).
    total_donations: Float,
    /// Line 11, total disbursements/obligations this statement: "the sum
    /// total of disbursements itemized on Schedule 9B"
    /// ([fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
    /// Workbook rule "= Sum of F93 Disbursements". Column
    /// `total_disbursements` (FEC format workbook v8.4, sheet F9, field 39,
    /// labelled line 10 there).
    total_disbursements: Float,
    /// "TYPE OR PRINT NAME OF PERSON COMPLETING FORM", certifying "under
    /// penalty of perjury" that the statement is true, correct and complete
    /// ([fecfrm9.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=1)).
    /// Columns `person_completing_last_name`, `_first_name`, `_middle_name`,
    /// `_prefix`, `_suffix` (FEC format workbook v8.4, sheet F9, fields
    /// 40-44).
    person_completing: PersonName,
    /// Date signed. Column `date_signed` (FEC format workbook v8.4, sheet F9,
    /// field 45).
    date_signed: Option(calendar.Date),
  )
}

/// Form 9 Line 9, custodian of records.
pub type Form9Custodian {
  Form9Custodian(
    /// Line 9(a), name. Columns `custodian_last_name`, `custodian_first_name`,
    /// `custodian_middle_name`, `custodian_prefix`, `custodian_suffix` (FEC
    /// format workbook v8.4, sheet F9, fields 26-30).
    name: PersonName,
    /// Lines 9(b)-(c), address. Columns `custodian_street_1`,
    /// `custodian_street_2`, `custodian_city`, `custodian_state`,
    /// `custodian_zip_code` (FEC format workbook v8.4, sheet F9, fields
    /// 31-35).
    address: Address,
    /// Line 9(d), "Name of Employer or Principal Place of Business". Column
    /// `custodian_employer` (FEC format workbook v8.4, sheet F9, field 36).
    employer: Option(String),
    /// Line 9(e), occupation. Column `custodian_occupation` (FEC format
    /// workbook v8.4, sheet F9, field 37).
    occupation: Option(String),
  )
}
