//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form3x`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{
  type Address, type DetailedSummaryRow, type PersonName,
}

/// FEC Form 3X, the periodic report of receipts and disbursements filed by
/// "any political committee which is not an authorized committee" — party
/// committees and PACs. Committees authorized by House/Senate candidates file
/// Form 3 and presidential committees Form 3P instead
/// ([fecfrm3xi.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=3)).
///
/// # Columns A and B
///
/// Both summary pages have two columns: **Column A, "This Period"** and
/// **Column B, "Calendar Year-to-Date"**
/// ([fecfrm3x.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=2),
/// [p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=3)).
/// Unlike Forms 3 and 3P, Column B is *not* election-cycle-to-date: it resets
/// each January, is the previous report's year-to-date figure plus this
/// report's Column A, and on the first report of a calendar year equals
/// Column A ([fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
/// Every `DetailedSummaryRow` in this struct has `column_a` = This Period and
/// `column_b` = Calendar Year-to-Date.
///
/// Some Summary Page lines exist in only one column: cash on hand January 1
/// (Line 6(a)) only in Column B, cash at the beginning of the period (6(b))
/// and debts (Lines 9, 10) only in Column A (workbook fields 23, 28–29, 74–75).
/// Those are plain `f64`s, not rows.
pub type Form3X {
  Form3X(
    /// Form type as filed, e.g. `F3XN`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F3X`, field 1;
    /// allowed values "F3X+[N|A|T]"). The form prints Line 3 "IS THIS REPORT
    /// NEW (N) OR AMENDED (A)"
    /// ([fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1));
    /// neither the form nor the workbook defines the `T` suffix.
    form_type: String,
    /// Line 2, "FEC Identification Number" of the filing committee
    /// (`filer_committee_id_number`, workbook field 2;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    filer_committee_id: String,
    /// Line 1, "Name of Committee (in full)" (`committee_name`, workbook
    /// field 3; [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    committee_name: String,
    /// Committee mailing address from Line 1 (`street_1`, `street_2`, `city`,
    /// `state`, `zip_code`; workbook fields 5–9;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    address: Address,
    /// The page 1 checkbox "Check if different than previously reported.
    /// (ACC)" beside the address (`change_of_address`, workbook field 4,
    /// "X = Yes"; [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    change_of_address: Bool,
    /// Line 4, "Type of Report": the code printed beside the checked box —
    /// `Q1`–`Q3`, `YE`, `MY`, `TER`, `M2`–`M12`, `12P`/`12G`/`12R`/`12C`/`12S`,
    /// `30G`/`30R`/`30S` ([fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    /// A monthly filer's year-end report is coded `MYE` (`report_code`,
    /// workbook field 10). See `Form3X::report_code_label`.
    report_code: Option(String),
    /// Election code for pre- and post-election reports, e.g. `P2012`
    /// (`election_code`, workbook field 11, allowed values
    /// "C,G,P,R,S,E\[YYYY\]"). The paper form has no box for it; its letter
    /// matches the Primary/General/Runoff/Convention/Special checkbox of
    /// Line 4(c)/(d) ([fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    /// Absent from the paper (`P*`) layouts. See `Form3X::election_code_label`.
    election_code: Option(String),
    /// Line 4(c)/(d) "Election on MM/DD/YYYY" — the election a 12-day
    /// pre-election or 30-day post-election report is for
    /// (`date_of_election`, workbook field 12;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    election_date: Option(calendar.Date),
    /// Line 4(c)/(d) "in the State of" for that election
    /// (`state_of_election`, workbook field 13;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    state_of_election: Option(String),
    /// Line 5, "Covering Period" start date (`coverage_from_date`, workbook
    /// field 14; [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    coverage_from_date: Option(calendar.Date),
    /// Line 5, "Covering Period ... through" end date
    /// (`coverage_through_date`, workbook field 15;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    coverage_through_date: Option(calendar.Date),
    /// Summary Page checkbox "This committee has qualified as a multicandidate
    /// committee. (see FEC FORM 1M)" (`qualified_committee`, workbook field 16,
    /// "X = Yes"; [fecfrm3x.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=2)).
    /// The instructions say to check it if the committee "has qualified as a
    /// 'multicandidate committee' and has filed FORM 1M"
    /// ([fecfrm3xi.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=5)).
    qualified_committee: Bool,
    /// "Type or Print Name of Treasurer" on page 1 (`treasurer_last_name`,
    /// `treasurer_first_name`, `treasurer_middle_name`, `treasurer_prefix`,
    /// `treasurer_suffix`; workbook fields 17–21;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    ///
    /// v1–v5 records have one `treasurer_name` column instead, sub-delimited
    /// as "Lastname^Firstname^Prefix^Suffix" (FEC format v5.30 documentation,
    /// `FEC_v530.rtf`, "Individual's Names"); it is split on `^` into those
    /// parts, and the middle name is left empty.
    treasurer: PersonName,
    /// Date the treasurer signed, beside "Signature of Treasurer" on page 1
    /// (`date_signed`, workbook field 22;
    /// [fecfrm3x.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=1)).
    date_signed: Option(calendar.Date),
    /// Page 2, the Summary Page (Lines 6–10).
    summary: Form3XSummary,
    /// Pages 3–5, the Detailed Summary Page (Lines 11–38).
    detailed_summary: Form3XDetailedSummary,
  )
}

/// Page 2, the Summary Page (Lines 6–10)
/// ([fecfrm3x.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=2)).
/// Column A is This Period, Column B Calendar Year-to-Date; see `Form3X`.
/// Filers complete the Detailed Summary first and carry its totals here
/// ([fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
pub type Form3XSummary {
  Form3XSummary(
    /// Line 6(a), "Cash on Hand January 1, YYYY": cash on hand at the
    /// beginning of the calendar year. **Column B only**
    /// (`col_b_cash_on_hand_jan_1`, workbook field 74;
    /// [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line6a_cash_on_hand_jan_1: Float,
    /// The year printed after "January 1," on Line 6(a) (`col_b_year`,
    /// workbook field 75, "Year for Above";
    /// [fecfrm3x.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=2)).
    line6a_year: Option(Int),
    /// Line 6(b), "Cash on Hand at Beginning of Reporting Period". **Column A
    /// only** (`col_a_cash_on_hand_beginning_period`, workbook field 23;
    /// [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line6b_cash_on_hand_beginning_period: Float,
    /// Line 6(c), "Total Receipts (from Line 19)" (`col_a_total_receipts`,
    /// `col_b_total_receipts`; workbook fields 24, 76, rule "= 19";
    /// [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line6c_total_receipts: DetailedSummaryRow,
    /// Line 6(d), "Subtotal": 6(b) + 6(c) in Column A, 6(a) + 6(c) in Column B
    /// (`col_a_subtotal`, `col_b_subtotal`; workbook fields 25, 77;
    /// [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line6d_subtotal: DetailedSummaryRow,
    /// Line 7, "Total Disbursements (from Line 31)"
    /// (`col_a_total_disbursements`, `col_b_total_disbursements`; workbook
    /// fields 26, 78; [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line7_total_disbursements: DetailedSummaryRow,
    /// Line 8, "Cash on Hand at Close of Reporting Period" = 6(d) − 7, which
    /// "should be the same for both columns"
    /// (`col_a_cash_on_hand_close_of_period`,
    /// `col_b_cash_on_hand_close_of_period`; workbook fields 27, 79;
    /// [fecfrm3xi.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=4)).
    line8_cash_on_hand_close_of_period: DetailedSummaryRow,
    /// Line 9, "Debts and Obligations Owed TO the Committee", the total from
    /// Schedule C and/or D. **Column A only** (`col_a_debts_to`, workbook
    /// field 28; [fecfrm3xi.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=5)).
    line9_debts_owed_to_committee: Float,
    /// Line 10, "Debts and Obligations Owed BY the Committee", the total from
    /// Schedule C and/or D. **Column A only** (`col_a_debts_by`, workbook
    /// field 29; [fecfrm3xi.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=5)).
    line10_debts_owed_by_committee: Float,
  )
}

/// Pages 3–5, the Detailed Summary Page
/// ([fecfrm3x.pdf p3–5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=3)),
/// in the form's three sections. Column A is This Period, Column B Calendar
/// Year-to-Date; see `Form3X`.
pub type Form3XDetailedSummary {
  Form3XDetailedSummary(
    /// Section I, Receipts (Lines 11–20).
    receipts: Form3XReceipts,
    /// Section II, Disbursements (Lines 21–32).
    disbursements: Form3XDisbursements,
    /// Section III, Net Contributions/Operating Expenditures (Lines 33–38).
    net: Form3XNetContributionsAndOperatingExpenditures,
  )
}

/// Detailed Summary Page, Section I — Receipts, Lines 11–20
/// ([fecfrm3x.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=3);
/// line instructions [fecfrm3xi.pdf p6–7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
pub type Form3XReceipts {
  Form3XReceipts(
    /// Line 11(a)(i), contributions from individuals/persons other than
    /// political committees, itemized on Schedule A (persons aggregating over
    /// $200 in the calendar year) (`col_a_individuals_itemized`,
    /// `col_b_individuals_itemized`; workbook fields 30, 80;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11a_i_individuals_itemized: DetailedSummaryRow,
    /// Line 11(a)(ii), contributions from individuals/persons not required to
    /// be itemized (`col_a_individuals_unitemized`,
    /// `col_b_individuals_unitemized`; workbook fields 31, 81;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11a_ii_individuals_unitemized: DetailedSummaryRow,
    /// Line 11(a)(iii), total from individuals/persons = 11(a)(i) + (ii)
    /// (`col_a_individual_contribution_total`,
    /// `col_b_individual_contribution_total`; workbook fields 32, 82;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11a_iii_individuals_total: DetailedSummaryRow,
    /// Line 11(b), contributions from political party committees — for
    /// committees other than party committees, which use Line 12
    /// (`col_a_political_party_committees`,
    /// `col_b_political_party_committees`; workbook fields 33, 83;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11b_political_party_committees: DetailedSummaryRow,
    /// Line 11(c), contributions from other political committees such as PACs
    /// (`col_a_other_political_committees_pacs`,
    /// `col_b_other_political_committees_pacs`; workbook fields 34, 84;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11c_other_political_committees: DetailedSummaryRow,
    /// Line 11(d), total contributions = 11(a)(iii) + 11(b) + 11(c)
    /// (`col_a_total_contributions`, `col_b_total_contributions`; workbook
    /// fields 35, 85; [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line11d_total_contributions: DetailedSummaryRow,
    /// Line 12, transfers from affiliated/other party committees, including
    /// loans and loan repayments from them
    /// (`col_a_transfers_from_aff_other_party_cmttees`,
    /// `col_b_transfers_from_aff_other_party_cmttees`; workbook fields 36, 86;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line12_transfers_from_affiliated: DetailedSummaryRow,
    /// Line 13, all loans received, other than from affiliated/party
    /// committees (`col_a_total_loans`, `col_b_total_loans`; workbook fields
    /// 37, 87; [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line13_loans_received: DetailedSummaryRow,
    /// Line 14, loan repayments received
    /// (`col_a_total_loan_repayments_received`,
    /// `col_b_total_loan_repayments_received`; workbook fields 38, 88;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line14_loan_repayments_received: DetailedSummaryRow,
    /// Line 15, offsets to operating expenditures (refunds, rebates, returns
    /// of deposits) (`col_a_offsets_to_expenditures`,
    /// `col_b_offsets_to_expenditures`; workbook fields 39, 89;
    /// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)).
    line15_offsets_to_operating_expenditures: DetailedSummaryRow,
    /// Line 16, refunds of contributions the committee made to federal
    /// candidates and other political committees (`col_a_federal_refunds`,
    /// `col_b_federal_refunds`; workbook fields 40, 90;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line16_refunds_of_federal_contributions: DetailedSummaryRow,
    /// Line 17, other federal receipts (dividends, interest, etc.)
    /// (`col_a_other_federal_receipts`, `col_b_other_federal_receipts`;
    /// workbook fields 41, 91;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line17_other_federal_receipts: DetailedSummaryRow,
    /// Line 18(a), transfers from the nonfederal account for allocated
    /// federal/nonfederal activity, from Schedule H3
    /// (`col_a_transfers_from_nonfederal_h3`,
    /// `col_b_transfers_from_nonfederal_h3`; workbook fields 42, 92;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line18a_transfers_from_nonfederal_account: DetailedSummaryRow,
    /// Line 18(b), transfers from Levin funds for allocated federal election
    /// activity, from Schedule H5 (`col_a_levin_funds`, `col_b_levin_funds`;
    /// workbook fields 43, 93;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    /// Not in v1–v3 layouts.
    line18b_transfers_from_levin_funds: DetailedSummaryRow,
    /// Line 18(c), total nonfederal transfers = 18(a) + 18(b)
    /// (`col_a_total_nonfederal_transfers`, `col_b_total_nonfederal_transfers`;
    /// workbook fields 44, 94;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    /// Not in v1–v3 layouts.
    line18c_total_nonfederal_transfers: DetailedSummaryRow,
    /// Line 19, total receipts = 11(d) + 12 + 13 + 14 + 15 + 16 + 17 + 18(c);
    /// carried to Line 6(c) (`col_a_total_receipts_TODO_DUP`,
    /// `col_b_total_receipts_TODO_DUP`, falling back to `col_*_total_receipts`
    /// in older layouts; workbook fields 45, 95;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    /// Includes nonfederal transfers in (18(c)).
    line19_total_receipts: DetailedSummaryRow,
    /// Line 20, total federal receipts = 19 − 18(c)
    /// (`col_a_total_federal_receipts`, `col_b_total_federal_receipts`;
    /// workbook fields 46, 96;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line20_total_federal_receipts: DetailedSummaryRow,
  )
}

/// Detailed Summary Page, Section II — Disbursements, Lines 21–32
/// ([fecfrm3x.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=4);
/// line instructions [fecfrm3xi.pdf p7–9](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
pub type Form3XDisbursements {
  Form3XDisbursements(
    /// Line 21(a)(i), shared federal/nonfederal operating expenditures,
    /// federal share, from Schedule H4
    /// (`col_a_shared_operating_expenditures_federal`,
    /// `col_b_shared_operating_expenditures_federal`; workbook fields 47, 97;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    /// Completed only by committees with allocated activity.
    line21a_i_shared_operating_federal_share: DetailedSummaryRow,
    /// Line 21(a)(ii), shared operating expenditures, nonfederal share, from
    /// Schedule H4 (`col_a_shared_operating_expenditures_nonfederal`,
    /// `col_b_shared_operating_expenditures_nonfederal`; workbook fields 48, 98;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line21a_ii_shared_operating_nonfederal_share: DetailedSummaryRow,
    /// Line 21(b), other federal operating expenditures, itemized and
    /// unitemized (`col_a_other_federal_operating_expenditures`,
    /// `col_b_other_federal_operating_expenditures`; workbook fields 49, 99;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line21b_other_federal_operating_expenditures: DetailedSummaryRow,
    /// Line 21(c), total operating expenditures = 21(a)(i) + 21(a)(ii) +
    /// 21(b) (`col_a_total_operating_expenditures`,
    /// `col_b_total_operating_expenditures`; workbook fields 50, 100;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line21c_total_operating_expenditures: DetailedSummaryRow,
    /// Line 22, transfers to affiliated/other party committees, including
    /// loans and loan repayments made to them
    /// (`col_a_transfers_to_affiliated`, `col_b_transfers_to_affiliated`;
    /// workbook fields 51, 101;
    /// [fecfrm3xi.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=7)).
    line22_transfers_to_affiliated: DetailedSummaryRow,
    /// Line 23, contributions to federal candidates/committees and other
    /// political committees, including in-kind
    /// (`col_a_contributions_to_candidates`,
    /// `col_b_contributions_to_candidates`; workbook fields 52, 102;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line23_contributions_to_federal_candidates: DetailedSummaryRow,
    /// Line 24, independent expenditures, from Schedule E
    /// (`col_a_independent_expenditures`, `col_b_independent_expenditures`;
    /// workbook fields 53, 103;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line24_independent_expenditures: DetailedSummaryRow,
    /// Line 25, coordinated party expenditures under 52 U.S.C. § 30116(d),
    /// from Schedule F; party committees only
    /// (`col_a_coordinated_expenditures_by_party_committees`,
    /// `col_b_coordinated_expenditures_by_party_committees`; workbook fields
    /// 54, 104; [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line25_coordinated_party_expenditures: DetailedSummaryRow,
    /// Line 26, loan repayments made (`col_a_total_loan_repayments_made`,
    /// `col_b_total_loan_repayments_made`; workbook fields 55, 105;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line26_loan_repayments_made: DetailedSummaryRow,
    /// Line 27, loans made, excluding transfers on Line 22
    /// (`col_a_loans_made`, `col_b_loans_made`; workbook fields 56, 106;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line27_loans_made: DetailedSummaryRow,
    /// Line 28(a), contribution refunds to individuals/persons other than
    /// political committees (`col_a_refunds_to_individuals`,
    /// `col_b_refunds_to_individuals`; workbook fields 57, 107;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line28a_refunds_to_individuals: DetailedSummaryRow,
    /// Line 28(b), contribution refunds to political party committees
    /// (`col_a_refunds_to_party_committees`,
    /// `col_b_refunds_to_party_committees`; workbook fields 58, 108;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line28b_refunds_to_party_committees: DetailedSummaryRow,
    /// Line 28(c), contribution refunds to other political committees
    /// (`col_a_refunds_to_other_committees`,
    /// `col_b_refunds_to_other_committees`; workbook fields 59, 109;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line28c_refunds_to_other_committees: DetailedSummaryRow,
    /// Line 28(d), total contribution refunds = 28(a) + 28(b) + 28(c)
    /// (`col_a_total_refunds`, `col_b_total_refunds`; workbook fields 60, 110;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line28d_total_contribution_refunds: DetailedSummaryRow,
    /// Line 29, other disbursements, including donations to nonfederal
    /// candidates (`col_a_other_disbursements`, `col_b_other_disbursements`;
    /// workbook fields 61, 111;
    /// [fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    line29_other_disbursements: DetailedSummaryRow,
    /// Line 30(a)(i), shared federal election activity, federal share, from
    /// Schedule H6 (`col_a_federal_election_activity_federal_share`,
    /// `col_b_federal_election_activity_federal_share`; workbook fields 62,
    /// 112; [fecfrm3x.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=4)).
    /// Only State, district and local party committees use Line 30
    /// ([fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8)).
    /// Not in v1–v3 layouts.
    line30a_i_fea_federal_share: DetailedSummaryRow,
    /// Line 30(a)(ii), shared federal election activity, "Levin" share, from
    /// Schedule H6 (`col_a_federal_election_activity_levin_share`,
    /// `col_b_federal_election_activity_levin_share`; workbook fields 63, 113;
    /// [fecfrm3x.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=4)).
    line30a_ii_fea_levin_share: DetailedSummaryRow,
    /// Line 30(b), federal election activity paid entirely with federal funds
    /// (`col_a_federal_election_activity_all_federal`,
    /// `col_b_federal_election_activity_all_federal`; workbook fields 64, 114;
    /// [fecfrm3xi.pdf p9](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=9)).
    line30b_fea_all_federal: DetailedSummaryRow,
    /// Line 30(c), total federal election activity = 30(a)(i) + 30(a)(ii) +
    /// 30(b) (`col_a_federal_election_activity_total`,
    /// `col_b_federal_election_activity_total`; workbook fields 65, 115;
    /// [fecfrm3xi.pdf p9](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=9)).
    line30c_fea_total: DetailedSummaryRow,
    /// Line 31, total disbursements = 21(c) + 22 + 23 + 24 + 25 + 26 + 27 +
    /// 28(d) + 29 + 30(c); carried to Line 7
    /// (`col_a_total_disbursements_TODO_DUP`,
    /// `col_b_total_disbursements_TODO_DUP`, falling back to
    /// `col_*_total_disbursements` in older layouts; workbook fields 66, 116;
    /// [fecfrm3xi.pdf p9](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=9)).
    /// Includes the nonfederal and Levin shares.
    line31_total_disbursements: DetailedSummaryRow,
    /// Line 32, total federal disbursements = 31 − 21(a)(ii) − 30(a)(ii)
    /// (`col_a_total_federal_disbursements`,
    /// `col_b_total_federal_disbursements`; workbook fields 67, 117;
    /// [fecfrm3xi.pdf p9](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=9)).
    line32_total_federal_disbursements: DetailedSummaryRow,
  )
}

/// Detailed Summary Page, Section III — Net Contributions/Operating
/// Expenditures, Lines 33–38: earlier lines repeated to compute two net
/// figures ([fecfrm3x.pdf p5](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3x.pdf#page=5)).
pub type Form3XNetContributionsAndOperatingExpenditures {
  Form3XNetContributionsAndOperatingExpenditures(
    /// Line 33, total contributions (other than loans), from Line 11(d)
    /// (`col_a_total_contributions_TODO_DUP`,
    /// `col_b_total_contributions_TODO_DUP`, falling back to
    /// `col_*_total_contributions` in older layouts; workbook fields 68, 118).
    line33_total_contributions: DetailedSummaryRow,
    /// Line 34, total contribution refunds, from Line 28(d)
    /// (`col_a_total_contributions_refunds`,
    /// `col_b_total_contributions_refunds`; workbook fields 69, 119).
    line34_total_contribution_refunds: DetailedSummaryRow,
    /// Line 35, net contributions (other than loans) = 33 − 34
    /// (`col_a_net_contributions`, `col_b_net_contributions`; workbook fields
    /// 70, 120).
    line35_net_contributions: DetailedSummaryRow,
    /// Line 36, total federal operating expenditures = 21(a)(i) + 21(b) —
    /// excludes the nonfederal share
    /// (`col_a_total_federal_operating_expenditures`,
    /// `col_b_total_federal_operating_expenditures`; workbook fields 71, 121).
    line36_total_federal_operating_expenditures: DetailedSummaryRow,
    /// Line 37, offsets to operating expenditures, from Line 15
    /// (`col_a_total_offsets_to_expenditures`,
    /// `col_b_total_offsets_to_expenditures`; workbook fields 72, 122).
    line37_offsets_to_operating_expenditures: DetailedSummaryRow,
    /// Line 38, net operating expenditures = 36 − 37
    /// (`col_a_net_operating_expenditures`, `col_b_net_operating_expenditures`;
    /// workbook fields 73, 123).
    line38_net_operating_expenditures: DetailedSummaryRow,
  )
}
