//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form1m`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address, type PersonName}

/// FEC Form 1M, **Notification of Multicandidate Status**.
///
/// The form "discloses supplemental information that verifies the date on
/// which your committee became a multicandidate committee". To qualify, a
/// political committee must (a) be registered for at least 6 months, (b)
/// receive contributions from more than 50 persons, and (c) make
/// contributions to at least 5 Federal candidates — (c) does not apply to
/// State party committees. It is filed within ten days after satisfying the
/// three requirements
/// ([fecfrm1mi.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1mi.pdf#page=1)).
///
/// The treasurer certifies that one of two situations is correct and
/// completes Line 4 *or* Line 5
/// ([fecfrm1m.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1m.pdf#page=1)):
///
/// - **Line 4, status by affiliation** (`Form1M::affiliation`): the
///   committee qualified through its affiliation with an existing
///   multicandidate committee.
/// - **Line 5, status by qualification** (`Form1M::qualification`): five
///   candidates it contributed to, plus the 51st-contributor, registration
///   and qualification dates.
///
/// The workbook makes each group all-or-nothing ("Req if any Affil fields
/// used", "Req if any 51st Contrib fields used"; FEC format workbook v8.4,
/// sheet `F1M`, fields 10–12 and 63–65), so normally one of the two is
/// `None`. Real filings occasionally populate both; both are kept.
pub type Form1M {
  Form1M(
    /// Form type as filed, e.g. `F1MN`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F1M`, field 1).
    form_type: String,
    /// Line 1(a) "Name of Committee in Full" (`committee_name`, field 3).
    committee_name: String,
    /// Line 1(b)–(c) mailing address (`street_1`, `street_2`, `city`, `state`,
    /// `zip_code`, fields 4–8).
    address: Address,
    /// Line 2 FEC identification number (`filer_committee_id_number`, field 2).
    filer_committee_id: String,
    /// Line 3 "Type of Committee (check one)": `X` = State party, `N` = other
    /// (`committee_type`, field 9). This is *not* the Form 1 committee type.
    /// See `Form1M::committee_type_label`.
    committee_type: Option(String),
    /// Line 4, status by affiliation (fields 10–12). `None` when all three
    /// columns are blank.
    affiliation: Option(Form1MAffiliation),
    /// Line 5, status by qualification (fields 13–65). `None` when every
    /// candidate column and all three dates are blank.
    qualification: Option(Form1MQualification),
    /// "Type or Print Name of Treasurer" (`treasurer_*`, fields 66–70; the
    /// single caret-delimited `treasurer_name` column of pre-v6 formats is
    /// split into parts).
    treasurer: PersonName,
    /// Date next to the treasurer's signature (`date_signed`, field 71).
    date_signed: Option(calendar.Date),
  )
}

/// Line 4, **status by affiliation**: "The committee submitted its Statement
/// of Organization (FEC FORM 1) on ___ and simultaneously qualified as a
/// multicandidate committee through its affiliation with: Committee Name: ___
/// FEC Identification Number: ___"
/// ([fecfrm1m.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1m.pdf#page=1)).
pub type Form1MAffiliation {
  Form1MAffiliation(
    /// Date the committee's Form 1 was submitted
    /// (`affiliated_date_f1_filed`, field 10).
    date_form1_filed: Option(calendar.Date),
    /// FEC ID of the affiliated multicandidate committee
    /// (`affiliated_committee_id_number`, field 11).
    committee_id: Option(String),
    /// Name of the affiliated multicandidate committee
    /// (`affiliated_committee_name`, field 12).
    committee_name: Option(String),
  )
}

/// Line 5, **status by qualification**
/// ([fecfrm1m.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1m.pdf#page=1),
/// [fecfrm1mi.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1mi.pdf#page=1)).
pub type Form1MQualification {
  Form1MQualification(
    /// Line 5(a) "Candidates: The committee has made contributions to the five
    /// (5) federal candidates listed below (ONLY State party committees may
    /// leave this blank.)": rows (i)–(v), from the `first_candidate_*` …
    /// `fifth_candidate_*` column groups (fields 13–62). Blank rows are
    /// omitted, so this has 0–5 entries in form order.
    candidates: List(Form1MCandidate),
    /// Line 5(b) "Contributors: The committee received a contribution from its
    /// 51st contributor on" (`fifty_first_contributor_date`, field 63).
    fifty_first_contributor_date: Option(calendar.Date),
    /// Line 5(c) "Registration: The committee has been registered for at least
    /// 6 months. FEC FORM 1 was submitted on" (`original_registration_date`,
    /// field 64).
    original_registration_date: Option(calendar.Date),
    /// Line 5(d) "Qualification: The committee met the above requirements on"
    /// (`requirements_met_date`, field 65): the date it "satisfied its final
    /// requirement for multicandidate status"
    /// ([fecfrm1mi.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1mi.pdf#page=1)).
    requirements_met_date: Option(calendar.Date),
  )
}

/// One row (i)–(v) of the Line 5(a) candidate table: "Name", "Office
/// Sought", "State/District", "Date"
/// ([fecfrm1m.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1m.pdf#page=1)).
/// Column names below use `first_` for row (i); rows (ii)–(v) use `second_`
/// … `fifth_` (fields 13–22, 23–32, 33–42, 43–52, 53–62).
pub type Form1MCandidate {
  Form1MCandidate(
    /// Candidate's FEC ID (`first_candidate_id_number`, field 13). The paper
    /// table has no ID column. In practice some filers enter the candidate's
    /// committee ID (`C…`) here; it is kept as filed.
    candidate_id: Option(String),
    /// "Name" (`first_candidate_last_name` … `first_candidate_suffix`,
    /// fields 14–18; the caret-delimited `first_candidate_name` of pre-v6
    /// formats is split into parts). Some filers enter a committee name here.
    name: PersonName,
    /// "Office Sought": `H`, `S` or `P` (`first_candidate_office`, field 19).
    /// See `Form1MCandidate::office_label`.
    office: Option(String),
    /// Candidate's state, for House and Senate (`first_candidate_state`,
    /// field 20).
    state: Option(String),
    /// Candidate's district, for House (`first_candidate_district`, field 21).
    district: Option(String),
    /// "Date" of the committee's contribution to this candidate
    /// (`first_candidate_contribution_date`, field 22).
    contribution_date: Option(calendar.Date),
  )
}
