//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers::form1`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address, type PersonName}

/// FEC Form 1, **Statement of Organization**: how a political committee
/// registers with the FEC, and how it reports later changes to that
/// registration.
///
/// "All political committees" file it, and Line 5 sorts them into ten types
/// (see `Form1::committee_type_label`). New committees file within 10 days
/// of the trigger that applies to them (designation on Form 2, establishment
/// of a separate segregated fund, or crossing a contribution/expenditure
/// threshold), and any change or correction must be reported within 10 days
/// ([fecfrm1i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=1)).
///
/// The paper form has nine lines: committee name and contact details
/// (Line 1), date (2), FEC ID (3), new/amended (4), type of committee (5),
/// connected organization / affiliated committee (6), custodian of records
/// (7), treasurer and designated agent (8) and banks or depositories (9)
/// ([fecfrm1.pdf p1–4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=1)).
/// Line 4 (new or amended) is the `N`/`A` suffix of `Form1::form_type`
/// (`F1N`/`F1A`, field 1); see `Form1::is_amendment`.
///
/// **Amendments.** The paper instructions ask amended statements to include
/// only the changes on Lines 5–9
/// ([fecfrm1i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=1)),
/// but electronic filers resubmit the entire form
/// ([colagui.pdf p22](https://www.fec.gov/resources/cms-content/documents/policy-guidance/colagui.pdf#page=22)),
/// so an `F1A` cover is a complete snapshot. The `change_of_*` flags mark
/// which Line 1 items changed.
///
/// **F1S supplements.** The cover record holds only the *first* connected
/// organization / affiliated committee / joint fundraising representative /
/// leadership PAC sponsor (Line 6), the first designated agent (Line 8) and
/// the first two banks (Line 9). Further instances — and every committee
/// participating in a joint fundraiser — are filed as separate `F1S` records
/// after the cover (FEC format workbook v8.4, sheet `F1`, notes before fields
/// 40, 78 and 90). This struct does not read `F1S` records; iterate the
/// filing's itemizations for those.
///
/// **Not on this record.** The committee "designation" and "filing frequency"
/// shown on fec.gov are not columns of the `F1` record in any format version,
/// so they are not here.
pub type Form1 {
  Form1(
    /// Form type as filed, e.g. `F1N`: the base form plus the
    /// amendment-indicator suffix (see `fec_parser::covers::base_form_type`).
    /// Column `form_type` (FEC format workbook v8.4, sheet `F1`, field 1).
    /// The suffix is Line 4, "Is this Statement New (N) or Amended (A)"
    /// ([fecfrm1.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=1)).
    form_type: String,
    /// Line 1, the committee's full name (`committee_name`, field 4).
    /// An authorized committee's name must include the candidate's name; a
    /// separate segregated fund's must include its connected organization's
    /// full name ([fecfrm1i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=1)).
    committee_name: String,
    /// Line 1 "(Check if name is changed)" box (`change_of_committee_name`,
    /// field 3, `X` = yes) ([fecfrm1.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=1)).
    change_of_committee_name: Bool,
    /// Line 1 mailing address (`street_1`, `street_2`, `city`, `state`,
    /// `zip_code`, fields 6–10).
    address: Address,
    /// Line 1 "(Check if address is changed)" box next to the mailing address
    /// (`change_of_address`, field 5, `X` = yes).
    change_of_address: Bool,
    /// Line 1 "Committee's E-mail Address", plus the "Optional Second E-Mail
    /// Address" (`committee_email`, field 12). The workbook allows at most two
    /// addresses "delimited by a semi-colon or a comma"; the raw value is kept
    /// as filed.
    committee_email: Option(String),
    /// "(Check if address is changed)" box next to the e-mail address
    /// (`change_of_committee_email`, field 11, `X` = yes).
    change_of_committee_email: Bool,
    /// Line 1 "Committee's Web Page Address (URL)" (`committee_url`, field 14):
    /// the committee's official web site, "if such a Web site exists"
    /// ([fecfrm1i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=1)).
    /// Kept as filed; it often lacks a scheme.
    committee_url: Option(String),
    /// "(Check if address is changed)" box next to the URL
    /// (`change_of_committee_url`, field 13, `X` = yes).
    change_of_committee_url: Bool,
    /// Line 2 "Date" (`effective_date`, field 15): the date the group became a
    /// political committee or, on an amendment, the date of the change
    /// ([fecfrm1i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=1)).
    effective_date: Option(calendar.Date),
    /// Line 3 FEC identification number (`filer_committee_id_number`, field 2).
    filer_committee_id: String,
    /// Line 5 type of committee, one letter `A`–`J` for boxes 5(a)–5(j)
    /// (`committee_type`, field 22). See `Form1::committee_type_label`.
    committee_type: Option(String),
    /// Line 5(a)/(b)/(c) candidate, for candidate committees and committees
    /// supporting or opposing one candidate. `None` when every candidate
    /// column is blank.
    candidate: Option(Form1Candidate),
    /// Line 5 "Party Affiliation" of the candidate (5(a)/(b)) or the party of a
    /// party committee (5(d)), as an abbreviation such as `DEM`, `REP`
    /// (`party_code`, field 32). See `Form1::party_code_label`.
    party_code: Option(String),
    /// Line 5(d) level of a party committee: `NAT`, `STA` or `SUB`
    /// (`party_type`, field 33). See `Form1::party_type_label`.
    party_type: Option(String),
    /// Line 5(e) kind of connected organization of a separate segregated fund:
    /// `C`, `T`, `L`, `M`, `V` or `W` (`organization_type`, field 34). See
    /// `Form1::organization_type_label`.
    organization_type: Option(String),
    /// Lobbyist/Registrant PAC and Leadership PAC check boxes under Line 5.
    pac_flags: Form1PacFlags,
    /// Line 6, the first connected organization, affiliated committee, joint
    /// fundraising representative or leadership PAC sponsor (fields 40–53).
    /// Additional ones are on `F1S` records. `None` when every column is blank.
    /// Filers with nothing to list are told to enter "None" here
    /// ([fecfrm1i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=2)),
    /// so a committee name of `NONE` is common; it is kept as filed.
    affiliated: Option(Form1Affiliated),
    /// Line 7 custodian of records, "the person in possession of committee
    /// books and records" (`custodian_*`, fields 54–65). If the treasurer is
    /// the custodian, "the term 'treasurer' is sufficient"
    /// ([fecfrm1i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=3)).
    custodian: Option(Form1Contact),
    /// Line 8 treasurer (`treasurer_*`, fields 66–77). "Every political
    /// committee must have a treasurer"
    /// ([fecfrm1i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=3)).
    treasurer: Form1Contact,
    /// Line 8 first designated agent, "e.g., assistant treasurer"
    /// (`agent_*`, fields 78–89); further agents are on `F1S` records.
    agent: Option(Form1Contact),
    /// Line 9 banks or other depositories "in which the committee deposits
    /// funds, holds accounts, rents safety deposit boxes or maintains funds"
    /// ([fecfrm1.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=4)).
    /// At most two on the cover (`bank_*` fields 90–95, `bank2_*` fields
    /// 96–101); further depositories are on `F1S` records. Blank slots are
    /// omitted.
    banks: List(Form1Bank),
    /// "Type or Print Name of Treasurer" in the certification block on page 1
    /// (`signature_*`, fields 16–20): the person who signed the statement.
    signer: PersonName,
    /// Date next to the treasurer's signature (`date_signed`, field 21).
    date_signed: Option(calendar.Date),
  )
}

/// The candidate named under Line 5(a), 5(b) or 5(c).
///
/// Principal campaign and other authorized committees (5(a)/(b)) complete
/// name, office, state, district and party; a committee supporting or
/// opposing a single candidate (5(c)) gives the candidate's name
/// ([fecfrm1.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=2)).
pub type Form1Candidate {
  Form1Candidate(
    /// The candidate's FEC ID (`candidate_id_number`, field 23). Not printed
    /// on the paper form; often blank for new candidates.
    candidate_id: Option(String),
    /// "Name of Candidate" (`candidate_last_name` … `candidate_suffix`,
    /// fields 24–28; the single caret-delimited `candidate_name` column of
    /// pre-v6 formats is split into parts).
    name: PersonName,
    /// "Office Sought": `H`, `S` or `P` (`candidate_office`, field 29). See
    /// `Form1Candidate::office_label`.
    office: Option(String),
    /// Candidate's state, for House and Senate (`candidate_state`, field 30).
    state: Option(String),
    /// Candidate's district, for House (`candidate_district`, field 31).
    district: Option(String),
  )
}

/// The Line 5 Lobbyist/Registrant PAC and Leadership PAC check boxes.
///
/// The paper form repeats "In addition, this committee is a Lobbyist/Registrant
/// PAC" under boxes 5(e), 5(f), 5(g) and 5(h), and has one "Leadership PAC"
/// box under 5(f) ([fecfrm1.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=2));
/// each box is its own column, `X` = yes (fields 35–39). The 5(g) and 5(h)
/// columns exist from format v8.4 on; earlier records read as `false`.
pub type Form1PacFlags {
  Form1PacFlags(
    /// 5(e) separate segregated fund is also a Lobbyist/Registrant PAC
    /// (`lobbyist_registrant_pac`, field 35).
    lobbyist_registrant_pac_ssf: Bool,
    /// 5(f) nonconnected committee is also a Lobbyist/Registrant PAC
    /// (`lobbyist_registrant_pac_2`, field 36).
    lobbyist_registrant_pac_nonconnected: Bool,
    /// 5(f) nonconnected committee is also a Leadership PAC, whose sponsor is
    /// identified on Line 6 (`leadership_pac`, field 37). Per the instructions
    /// this box is checked when the committee "is directly or indirectly
    /// established, financed, maintained or controlled by a federal candidate
    /// or officeholder, but is not an authorized committee or party"
    /// ([fecfrm1i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1i.pdf#page=2)).
    leadership_pac: Bool,
    /// 5(g) Super PAC is also a Lobbyist/Registrant PAC
    /// (`lobbyist_registrant_pac_3`, field 38).
    lobbyist_registrant_pac_super_pac: Bool,
    /// 5(h) Hybrid PAC is also a Lobbyist/Registrant PAC
    /// (`lobbyist_registrant_pac_4`, field 39).
    lobbyist_registrant_pac_hybrid_pac: Bool,
  )
}

/// Line 6: a connected organization, affiliated committee, joint fundraising
/// representative/participant or leadership PAC sponsor.
///
/// Which one is given by `Form1Affiliated::relationship_code`. Committees
/// and organizations are named in `committee_name` (with `committee_id`); an
/// individual, such as a leadership PAC's sponsoring candidate or
/// officeholder, is named in `name` (with `candidate_id`) (FEC format
/// workbook v8.4, sheet `F1`, fields 40–53).
pub type Form1Affiliated {
  Form1Affiliated(
    /// FEC ID of the affiliated committee (`affiliated_committee_id_number`,
    /// field 40). Not printed on the paper form.
    committee_id: Option(String),
    /// "Name of Any Connected Organization, Affiliated Committee, Joint
    /// Fundraising Representative, or Leadership PAC Sponsor"
    /// (`affiliated_committee_name`, field 41).
    committee_name: Option(String),
    /// FEC candidate ID of an individual named here
    /// (`affiliated_candidate_id_number`, field 42).
    candidate_id: Option(String),
    /// Individual's name (`affiliated_last_name` … `affiliated_suffix`,
    /// fields 43–47).
    name: PersonName,
    /// Mailing address (`affiliated_street_1` … `affiliated_zip_code`,
    /// fields 48–52).
    address: Address,
    /// "Relationship": `ORG`, `AFF`, `JFR` or `LPS`
    /// (`affiliated_relationship_code`, field 53). See
    /// `Form1Affiliated::relationship_label`.
    relationship_code: Option(String),
  )
}

/// A person listed on Lines 7–8: custodian of records, treasurer or
/// designated agent. Each has a name, mailing address, "Title or Position"
/// and optional "Telephone number"
/// ([fecfrm1.pdf p3–4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=3)).
pub type Form1Contact {
  Form1Contact(
    /// Full name (`{role}_last_name` … `{role}_suffix`; the single
    /// caret-delimited `{role}_name` column of pre-v6 formats is split into
    /// parts).
    name: PersonName,
    /// Mailing address (`{role}_street_1` … `{role}_zip_code`).
    address: Address,
    /// "Title or Position" (`{role}_title`).
    title: Option(String),
    /// "Telephone number" (`{role}_telephone`, ten digits, kept as filed).
    telephone: Option(String),
  )
}

/// Line 9: a bank, depository, etc. — "Name of Bank, Depository, etc." and
/// its mailing address ([fecfrm1.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm1.pdf#page=4)).
pub type Form1Bank {
  Form1Bank(
    /// `bank_name` / `bank2_name` (fields 90 and 96).
    name: Option(String),
    /// `bank_street_1` … `bank_zip_code` (fields 91–95) or `bank2_*` (97–101).
    address: Address,
  )
}
