//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import libfec/cover/common.{type Address, type PersonName}

/// The other party to an itemized transaction: a contributor, payee, lender
/// or creditor. The FEC format gives each one an `entity_type` code, an
/// organization name (required unless the entity is an individual or a
/// candidate) and a person's name (required for those two), and an address
/// (e.g. FEC format workbook v8.4, sheet `Sch A`, fields 6–17).
pub type Entity {
  Entity(
    /// `IND`, `ORG`, `COM`, … — see `Entity::entity_type_label`. Absent
    /// before v5.0 and on paper filings.
    entity_type: Option(String),
    /// The organization's name, for anything but a person.
    organization_name: Option(String),
    /// The person's name, for an individual or a candidate.
    name: PersonName,
    address: Address,
  )
}

/// A federal candidate an itemization names: the donor candidate of a
/// receipt, the beneficiary of a disbursement, the candidate an independent
/// expenditure supports or opposes. Office is `H`, `S` or `P`; state and
/// district identify the seat (e.g. FEC format workbook v8.4, sheet `Sch A`,
/// fields 28–36).
pub type CandidateRef {
  CandidateRef(
    /// The candidate's FEC ID (`H0VA01234`).
    fec_id: Option(String),
    name: PersonName,
    /// `H` House, `S` Senate, `P` President; see `CandidateRef::office_label`.
    office: Option(String),
    state: Option(String),
    district: Option(String),
  )
}
