//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::form9_items`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address, type PersonName} as _
import libfec/itemization/common.{type CandidateRef, type Entity} as _

/// One person listed under Form 9 Line 12, "Person(s) Sharing/Exercising
/// Control": "officers, directors, executive directors or their
/// equivalents, partners, and, in the case of unincorporated organizations,
/// owners of the entity or persons making disbursements" who "shared or
/// exercised control of making the disbursement/obligation for the
/// electioneering communication" (instructions revised 01/2018)
/// ([fecfrm9.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=2),
/// [fecfrm9i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
/// The `F91` record (FEC format workbook v8.4, sheet `F91`, "FORM 9 / PERSONS
/// SHARING/EXERCISING CONTROL (FOR EACH PERSON)"); it has no amounts.
///
/// # Versions
///
/// v6.1–8.5 share the 15-field layout. v5.x has one combined name, read
/// from the `controller_last_name` column (FEC format workbook v5.3, sheet
/// `F91`, field 3, "IND/NAME") and split on the name delimiter, and the
/// transaction ID at the end. Paper layouts have no transaction ID but carry
/// an `image_number`.
pub type Form9ControllingPerson {
  Form9ControllingPerson(
    /// The row type as filed, `F91`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F91`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this row, unique for the life of the report;
    /// electronic-only. Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// "(a) Name". Columns `controller_last_name` … `controller_suffix`
    /// (fields 4–8).
    name: PersonName,
    /// "(b) Address" and "(c) City, State and ZIP Code". Columns
    /// `controller_street_1` … `controller_zip_code` (fields 9–13).
    address: Address,
    /// "(d) Name of Employer or Principal Place of Business". Column
    /// `controller_employer` (field 14).
    employer: Option(String),
    /// "(e) Occupation". Column `controller_occupation` (field 15).
    occupation: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// "SCHEDULE 9-A Donation(s) Received": one donation used to finance an
/// electioneering communication — "any gift, subscription, loan, advance or
/// deposit of money or anything of value" (instructions revised 01/2018)
/// ([fecfrm9.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=3),
/// [fecfrm9i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=1)).
/// The `F92` record (FEC format workbook v8.4, sheet `F92`, "FORM 9 / SCHED
/// 9-A - FOR EACH DONATION RECEIVED"). The cover's `total_donations` is "=
/// Sum of F92 Donations" (sheet `F9`, field 38).
///
/// Which donors appear depends on the filer: generally each donor of
/// $1,000 or more since the first day of the preceding calendar year, but a
/// corporation or labor organization not paying from a segregated account
/// lists only donations made "for the purpose of furthering electioneering
/// communications" ([fecfrm9i.pdf p2–3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=2)).
///
/// # Versions
///
/// v6.1–8.5 share the 19-field layout. The v5.x `F92` layout is the
/// Schedule A one (see the module docs): a combined `contributor_name` until
/// v5.1 added the separate name columns, employer and occupation, and a
/// "TRANS CODE"; its election code and aggregate are marked "Not used" and
/// its fields 18–33 are space holders (FEC format workbook v5.3, sheet
/// `F92`), so they are not read. Paper layouts have no transaction ID,
/// back reference or entity type but carry a memo text and an
/// `image_number`.
pub type Form9Donation {
  Form9Donation(
    /// The row type as filed, `F92`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F92`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// "Reference to the Tran ID of a Related Record". Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that record, `F92` or `F93`. Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// "Full Name of Donor" and "Mailing Address of Donor"
    /// ([fecfrm9.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=3)),
    /// though the columns say contributor. Columns `entity_type`,
    /// `contributor_organization_name`, `contributor_last_name` …
    /// `contributor_suffix`, `contributor_street_1` … `contributor_zip_code`
    /// (fields 6–17); v5.0 `contributor_name`.
    donor: Entity,
    /// "Date of Receipt" (DATE RECEIVED). Column `contribution_date`
    /// (field 18).
    contribution_date: Option(calendar.Date),
    /// "Amount" (AMOUNT RECEIVED). Column `contribution_amount` (field 19).
    contribution_amount: Float,
    /// v5.x only, "INDEMP", required "if Aggr > 200" (FEC format workbook
    /// v5.3, sheet `F92`, field 12); the v6+ record and the printed schedule
    /// have no employer. Column `contributor_employer`.
    donor_employer: Option(String),
    /// v5.x only, "INDOCC" (field 13). Column `contributor_occupation`.
    donor_occupation: Option(String),
    /// v5.x only, "TRANS CODE", sample `15`, values `15,15C,...` (FEC format
    /// workbook v5.3, sheet `F92`, field 17). Column
    /// `contribution_purpose_code`.
    transaction_code: Option(String),
    /// Paper layouts only. Column `memo_text_description`.
    memo_text: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// "SCHEDULE 9-B Disbursement(s) Made or Obligation(s)": one disbursement
/// made or contract executed for an electioneering communication,
/// "including each disbursement made or contract executed prior to
/// exceeding the $10,000 threshold" (instructions revised 01/2018)
/// ([fecfrm9.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=4),
/// [fecfrm9i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=3)).
/// The `F93` record (FEC format workbook v8.4, sheet `F93`, "FORM 9 / SCHED
/// 9-B - FOR EACH DISBURSEMENT MADE"). The cover's `total_disbursements` is
/// "= Sum of F93 Disbursements" (sheet `F9`, field 39). The candidates the
/// communication identifies are `Form9Candidate` (`F94`) rows that
/// back-reference this one's `transaction_id`.
///
/// # Versions
///
/// v8.0–8.5 have the 25-field layout; v6.1–7.0 add
/// `expenditure_purpose_code`. The v5.x `F93` layout is the Schedule B one
/// (see the module docs): a combined `payee_name` until v5.1 added the
/// separate name columns, a purpose code, a category code (fields 10, 36)
/// and the transaction ID near the end; its fields 16–30 are space holders
/// (FEC format workbook v5.3, sheet `F93`), so the beneficiary and conduit
/// columns the layout names there are not read. Paper layouts have no back
/// reference, entity type or election code but carry a memo text (P1–P3.1)
/// and an `image_number`.
pub type Form9Disbursement {
  Form9Disbursement(
    /// The row type as filed, `F93`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F93`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report. Column `transaction_id` (field 3); v5.x
    /// `transaction_id_number`.
    transaction_id: Option(String),
    /// "Reference to the Tran ID of a Related Record". Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that record, `F92` or `F93`. Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// "Full Name (Last, First, Middle Initial) of Payee" and "Mailing
    /// Address of Payee"
    /// ([fecfrm9.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=4)).
    /// Columns `entity_type`, `payee_organization_name`, `payee_last_name` …
    /// `payee_suffix`, `payee_street_1` … `payee_zip_code` (fields 6–17);
    /// v5.0 `payee_name`.
    payee: Entity,
    /// "Disbursement/Obligation For:" the election, a letter and a year
    /// (`G,P,O[YYYY]`). See `Form9Disbursement::election_code_label`.
    /// Column `election_code` (field 18).
    election_code: Option(String),
    /// "Other (specify)", required when `election_code` is `O…`. Column
    /// `election_other_description` (field 19).
    election_other_description: Option(String),
    /// "Date of Disbursement or Obligation". Column `expenditure_date`
    /// (field 20).
    expenditure_date: Option(calendar.Date),
    /// "Amount". Column `expenditure_amount` (field 21).
    expenditure_amount: Float,
    /// v5.0–7.0 only: "TRANS {Purpose} CODE" (FEC format workbook v5.3,
    /// sheet `F93`, field 10). Column `expenditure_purpose_code`.
    expenditure_purpose_code: Option(String),
    /// "Purpose of Disbursement (Including title(s) of communication(s))":
    /// the specific purpose (radio ad, television ad, …) and "the title of
    /// the communication as named by the media vendor or producer"
    /// ([fecfrm9i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=3)).
    /// Column `expenditure_purpose_descrip` (field 22).
    expenditure_purpose_description: Option(String),
    /// v5.x only: "CATEGORY CODE", `001`–`010` in the v5.3 workbook (sheet
    /// `F93`, field 36). Column `category_code`.
    category_code: Option(String),
    /// "Name of Employer", required if the payee is an individual or
    /// candidate. Column `payee_employer` (field 23).
    payee_employer: Option(String),
    /// "Occupation", same rule. Column `payee_occupation` (field 24).
    payee_occupation: Option(String),
    /// "Communication Date", which "in most instances … will be the Date of
    /// Public Distribution"
    /// ([fecfrm9i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=3)).
    /// Column `communication_date` (field 25).
    communication_date: Option(calendar.Date),
    /// Paper layouts P1–P3.1 only. Column `memo_text_description`.
    memo_text: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// One federal candidate "clearly identified in the communication" a
/// Schedule 9-B disbursement paid for, "including the office sought and the
/// election that the disbursement/obligation is made for" (instructions
/// revised 01/2018)
/// ([fecfrm9i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9i.pdf#page=3)).
/// On paper these are the repeated candidate blocks of a 9-B entry
/// ([fecfrm9.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm9.pdf#page=4));
/// electronically each is an `F94` row (FEC format workbook v8.4, sheet
/// `F94`, "FORM 94 - FEDERAL CANDIDATE LIST FOR FORM 93 TRANSACTIONS") whose
/// back reference names the `Form9Disbursement`. It has no amount.
///
/// # Versions
///
/// v6.1–8.5 share the 16-field layout. v5.x has one combined
/// `candidate_name` (split per `CandidateRef::from_prefixed`) and the
/// transaction ID and back reference at the end (FEC format workbook v5.3,
/// sheet `F94`). Paper layouts have no transaction ID, back-reference
/// schedule or candidate ID but carry an `image_number`.
pub type Form9Candidate {
  Form9Candidate(
    /// The row type as filed, `F94`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F94`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this row, unique for the life of the report.
    /// Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// The `transaction_id` of the `Form9Disbursement` this candidate
    /// belongs to. Column `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// Always `F93`. Column `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// "Name of Federal Candidate", "Office Sought", "State", "District",
    /// plus the candidate's FEC ID (electronic-only). Columns
    /// `candidate_id_number`, `candidate_last_name` … `candidate_district`
    /// (fields 6–14); v5.x `candidate_name`.
    candidate: CandidateRef,
    /// "Disbursement/Obligation For:" the election, a letter and a year
    /// (`G,P,O[YYYY]`). See `Form9Candidate::election_code_label`. Column
    /// `election_code` (field 15).
    election_code: Option(String),
    /// "Other (specify)", required when `election_code` is `O…`. Column
    /// `election_other_description` (field 16).
    election_other_description: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
