//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::form7_items`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/itemization/common.{type CandidateRef}

/// One line of Form 7's "Summary of Communication Costs": a communication a
/// corporation or membership organization made to its restricted class, with
/// its type, the class it went to, its date, the candidate it supported or
/// opposed and its cost
/// ([fecfrm7.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm7.pdf#page=1),
/// [fecfrm7i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm7i.pdf#page=1)).
/// The `F76` record (FEC format workbook v8.4, sheet `F76`, "FORM 7.6 - FOR
/// EACH COMMUNICATION").
///
/// The cost is **per candidate**: a communication advocating several
/// candidates is allocated among them "in equal proportions" unless some are
/// emphasized (instructions revised 2/2001)
/// ([fecfrm7i.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm7i.pdf#page=1)),
/// so one mailing can be several rows. The cover's `total_costs` is the sum
/// of these rows (FEC format workbook v8.4, sheet `F7`, field 15).
///
/// # Versions
///
/// v6.1–8.5 share the 20-field layout. v1–5.x (FEC format workbook v5.3,
/// sheet `F76`) have one combined `candidate_name` (split per
/// `CandidateRef::from_prefixed`), no election-other description, and the
/// transaction ID at the end (none in v1); their `amended_cd` is ignored, as
/// the v5.3 specification says (`FEC_v530.rtf`, "Amend Code … Unused
/// Field"). Paper layouts have no transaction ID or candidate ID but carry
/// an `image_number`.
pub type Form7Communication {
  Form7Communication(
    /// The row type as filed, `F76`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F76`, field 1).
    form_type: String,
    /// The filing organization's FEC ID ("2. Identification Number").
    /// Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// "Type of Communication": the workbook allows `DM`, `TP`, `TM`, `O`
    /// (field 4) and the form prints Direct Mail, Telephone, Telegram and
    /// Other ([fecfrm7.pdf p1](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm7.pdf#page=1)),
    /// but no source pairs code with box, so the code is kept raw. Column
    /// `communication_type`.
    communication_type: Option(String),
    /// The type when it is "Other:". Column `communication_type_description`
    /// (field 5).
    communication_type_description: Option(String),
    /// "Class or Category Communicated With": the workbook allows `E`, `S`,
    /// `M` (field 6) and the form prints Executive/Administrative
    /// Personnel, Stockholders and Members; no source pairs code with box,
    /// so the code is kept raw. Column `communication_class`.
    communication_class: Option(String),
    /// "Date(s) of Communication". Column `communication_date` (field 7).
    communication_date: Option(calendar.Date),
    /// "Cost of Communication (Per Candidate)". Column `communication_cost`
    /// (field 8).
    communication_cost: Float,
    /// The candidate's "Primary or General Election", a letter and a year
    /// (`G,P,O[CCYY]`). See `Form7Communication::election_code_label`.
    /// Column `election_code` (field 9).
    election_code: Option(String),
    /// Required when `election_code` is `O…` (Other); v6.1+. Column
    /// `election_other_description` (field 10).
    election_other_description: Option(String),
    /// `S` or `O`, the printed "Check One: Support Oppose". See
    /// `Form7Communication::support_oppose_label`. Column
    /// `support_oppose_code` (field 11).
    support_oppose_code: Option(String),
    /// "Identify Candidate, Office Sought, District and State", plus the
    /// candidate's FEC ID (electronic-only). Columns `candidate_id_number`,
    /// `candidate_last_name` … `candidate_district` (fields 12–20); v1–5.x
    /// `candidate_name`.
    candidate: CandidateRef,
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
