//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::form5_items`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address} as _
import libfec/itemization/common.{type CandidateRef, type Entity} as _

/// "SCHEDULE 5-A ITEMIZED RECEIPTS": one contribution a person other than a
/// political committee received "for the purpose of furthering the
/// independent expenditures" it reports on Form 5, itemized when over $200
/// (instructions revised 09/2013)
/// ([fecfrm5.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=2),
/// [fecfrm5i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=2)).
/// The `F56` record (FEC format workbook v8.4, sheet `F56`, "FORM 5.6 - FOR
/// EACH CONTRIBUTION (SCHEDULE 5-A)").
///
/// The schedule's total is carried to Line 6 of Form 5, which also counts
/// unitemized contributions of $200 or less, so summing a filing's `F56`
/// rows can come out below the cover's total
/// ([fecfrm5i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=2)).
/// There is no aggregate column (FEC format workbook v8.4, sheet `F56`,
/// fields 1–20).
///
/// # Versions
///
/// v6.1–8.5 share the 20-field layout. v2–5.x (FEC format workbook v5.3,
/// sheet `F56`) have one combined `contributor_name` (split per
/// `Entity::from_prefixed`), the transaction ID at the end, and a
/// candidate (fields 15–19) and conduit (fields 20–25) that v6+ dropped; their
/// `amended_cd` is ignored ("Unused Field (it's defined, but ignored)", FEC
/// format specification v5.3, `FEC_v530.rtf`, "Amend Code"). v1 has no entity
/// type and no transaction ID (its `sequence_number` is not read). Paper
/// layouts have no transaction ID or entity type but carry an `image_number`.
pub type Form5Contribution {
  Form5Contribution(
    /// The row type as filed, `F56`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F56`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, "unique and UPPER CASE for the
    /// life of the report (original + all amendments)"; electronic-only.
    /// Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// Who gave: entity type, organization or person, mailing address
    /// ("A. Full Name", "Mailing Address" on
    /// [fecfrm5.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=2)).
    /// Columns `entity_type`, `contributor_organization_name`,
    /// `contributor_last_name` … `contributor_suffix`, `contributor_street_1`
    /// … `contributor_zip_code` (fields 4–15); v1–5.x `contributor_name`.
    contributor: Entity,
    /// "FEC ID number of contributing federal political committee"
    /// ([fecfrm5.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=2)).
    /// Column `contributor_fec_id` (field 16).
    contributor_fec_id: Option(String),
    /// "Date of Receipt". Column `contribution_date` (field 17).
    contribution_date: Option(calendar.Date),
    /// "Amount of Each Receipt this Period". Column `contribution_amount`
    /// (field 18).
    contribution_amount: Float,
    /// "Name of Employer". Column `contributor_employer` (field 19).
    contributor_employer: Option(String),
    /// "Occupation". Column `contributor_occupation` (field 20).
    contributor_occupation: Option(String),
    /// v2–5.x only: "FEC CANDIDATE ID NUMBER", "CANDIDATE NAME",
    /// "CAN/OFFICE", "CAN/STATE", "CAN/DIST" (FEC format workbook v5.3, sheet
    /// `F56`, fields 15–19). The workbook does not say what role the
    /// candidate plays. Columns `candidate_id`, `candidate_name`,
    /// `candidate_office`, `candidate_state`, `candidate_district`.
    candidate: CandidateRef,
    /// v2–5.x only: "CONDUIT NAME" (FEC format workbook v5.3, sheet `F56`,
    /// field 20). Column `conduit_name`.
    conduit_name: Option(String),
    /// v2–5.x only (fields 21–25). Columns `conduit_street_1` …
    /// `conduit_zip_code`.
    conduit_address: Address,
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// "SCHEDULE 5-E ITEMIZED INDEPENDENT EXPENDITURES": one independent
/// expenditure by a person other than a political committee, with the
/// payee, the federal candidate it supports or opposes, and the
/// calendar-year aggregate per election and office
/// ([fecfrm5.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=3)).
/// The `F57` record (FEC format workbook v8.4, sheet `F57`, "FORM 5.7 - FOR
/// EACH INDEPENDENT EXPENDITURE MADE (SCHEDULE 5-E)").
///
/// Entries are itemized "once the total of independent expenditures made
/// exceeds $250 per election in a calendar year"; the schedule's total,
/// including unitemized expenditures, is carried to Line 7 of Form 5
/// (instructions revised 09/2013)
/// ([fecfrm5i.pdf p2–3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=2)).
/// For the 24- and 48-hour reports filers aggregate "including enforceable
/// contracts obligating funds for disbursement" as of the first date of
/// public dissemination, so a row can be an obligation rather than a payment
/// ([fecfrm5i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=2)).
///
/// # Versions
///
/// v8.1–8.5 and v8.0 have the 33-field layout; v6.1–7.0 add
/// `expenditure_purpose_code`. v2–5.x (FEC format workbook v5.3, sheet `F57`)
/// have combined `payee_name` and `candidate_name` columns (split per
/// `Entity::from_prefixed` and `CandidateRef::from_prefixed`), a conduit
/// (fields 25–30) dropped in v6; v5.x add at the end the category and
/// purpose codes, the aggregate and the election code (fields 33–37). v2's
/// `payee_candidate_*` columns (v5.x's "Unused field" 20–24) and every
/// legacy `amended_code` are not read. v1 has no entity type or transaction
/// ID. Paper layouts have no transaction ID, entity type, candidate ID or
/// payee committee ID but carry an `image_number`.
pub type Form5Expenditure {
  Form5Expenditure(
    /// The row type as filed, `F57`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `F57`, field 1).
    form_type: String,
    /// The filer's FEC ID. Column `filer_committee_id_number` (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id_number` (field 3).
    transaction_id: Option(String),
    /// Who was paid: "Full Name (Last, First, Middle Initial) of Payee" and
    /// "Mailing Address"
    /// ([fecfrm5.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=3)).
    /// Columns `entity_type`, `payee_organization_name`, `payee_last_name` …
    /// `payee_suffix`, `payee_street_1` … `payee_zip_code` (fields 4–15);
    /// v1–5.x `payee_name`.
    payee: Entity,
    /// The payee's FEC committee ID; electronic-only (no box on the printed
    /// schedule). Column `payee_cmtte_fec_id_number` (field 23).
    payee_committee_fec_id: Option(String),
    /// "Disbursement For:" the election, a letter and a year (`P2024`; the
    /// workbook allows `G,P,O[CCYY]`). See `Form5Expenditure::election_code_label`.
    /// Column `election_code` (field 16).
    election_code: Option(String),
    /// Required when `election_code` is `O…` (Other). Column
    /// `election_other_description` (field 17).
    election_other_description: Option(String),
    /// "Date of Public Distribution/Dissemination" — not a payment date
    /// ([fecfrm5.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=3)).
    /// Column `dissemination_date` (field 18).
    dissemination_date: Option(calendar.Date),
    /// "Amount". Column `expenditure_amount` (field 19).
    expenditure_amount: Float,
    /// "Calendar Year-To-Date Per Election for Office Sought": "the total
    /// amount expended in the aggregate during the calendar year, per
    /// election, per office sought" — a running aggregate, not an amount to
    /// sum ([fecfrm5i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=3)).
    /// Column `calendar_y_t_d_per_election_office` (field 20).
    calendar_ytd_per_election_office: Option(Float),
    /// A coded purpose ("TRANS {Purpose} CODE", sample `24A, 24E`; FEC format
    /// workbook v5.3, sheet `F57`, field 34), v5.0–7.0 only. Column
    /// `expenditure_purpose_code`.
    expenditure_purpose_code: Option(String),
    /// "Purpose of Expenditure". Column `expenditure_purpose_descrip`
    /// (field 21).
    expenditure_purpose_description: Option(String),
    /// "Category/Type" code, `001`–`012` (field 22); "not intended to replace
    /// or to serve as a substitute for the 'purpose of disbursement'"
    /// ([fecfrm5i.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5i.pdf#page=3)).
    /// See `Form5Expenditure::category_code_label`. Column `category_code`;
    /// from v5.0.
    category_code: Option(String),
    /// `S` or `O`, the printed "Check One: Support / Oppose" (field 24). See
    /// `Form5Expenditure::support_oppose_label`. Column
    /// `support_oppose_code`.
    support_oppose_code: Option(String),
    /// "Name of Federal Candidate Supported or Opposed by Expenditure",
    /// "Office Sought", "State", "District"
    /// ([fecfrm5.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm5.pdf#page=3)),
    /// plus the candidate's FEC ID (electronic-only). Columns
    /// `candidate_id_number`, `candidate_last_name` … `candidate_district`
    /// (fields 25–33); v1–5.x `candidate_name`.
    candidate: CandidateRef,
    /// v2–5.x only: "CONDUIT NAME" (FEC format workbook v5.3, sheet `F57`,
    /// field 25). Column `conduit_name`.
    conduit_name: Option(String),
    /// v2–5.x only (fields 26–30). Columns `conduit_street_1` …
    /// `conduit_zip_code`.
    conduit_address: Address,
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
