//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::form13_items`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/itemization/common.{type Entity}

/// "SCHEDULE 13-A ITEMIZED DONATIONS ACCEPTED": one donation to an inaugural
/// committee, itemized "for each donation of money or anything of value
/// aggregating $200 or more", with "the aggregate total of donations
/// accepted to date from that donor" (instructions dated 10/2004)
/// ([fecfrm13.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13.pdf#page=2),
/// [fecfrm13i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13i.pdf#page=2)).
/// The `F132` record (FEC format workbook v8.4, sheet `F132`, "FORM 132 - FOR
/// EACH ITEMIZED DONATION ACCEPTED"). Itemized donations are added to those
/// itemized before and the sum goes on Line 5 of Form 13, so the cover total
/// is cumulative across filings
/// ([fecfrm13i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13i.pdf#page=2)).
/// Neither the printed schedule nor the record has employer or occupation.
///
/// # Versions
///
/// v6.1–8.5 share the 22-field layout. v5.2–5.3 put the transaction ID and
/// back reference at the end and have no memo columns (FEC format workbook
/// v5.3, sheet `F132`). Paper layouts have no transaction ID, back reference
/// or entity type but carry an `image_number` (and a memo code from P3.2).
pub type Form13Donation {
  Form13Donation(
    /// The row type as filed, `F132`. Column `form_type` (FEC format
    /// workbook v8.4, sheet `F132`, field 1).
    form_type: String,
    /// The inaugural committee's FEC ID. Column `filer_committee_id_number`
    /// (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id_number` (field 3).
    transaction_id: Option(String),
    /// "Reference to the Tran ID of a Related Record". Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that record (sample `F133`). Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// "Full Name (Last, First, Middle Initial) or Full Organization Name"
    /// and "Mailing Address" of the donor
    /// ([fecfrm13.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13.pdf#page=2)).
    /// Columns `entity_type`, `contributor_organization_name`,
    /// `contributor_last_name` … `contributor_suffix`, `contributor_street_1`
    /// … `contributor_zip` (fields 6–17).
    donor: Entity,
    /// "Date Donation Received". Column `donation_date` (field 18).
    donation_date: Option(calendar.Date),
    /// "Amount of This Donation". Column `donation_amount` (field 19).
    donation_amount: Float,
    /// "Donor's Aggregate Donations To Date": a running figure per donor;
    /// sum `donation_amount`, not this. Column `donation_aggregate_amount`
    /// (field 20).
    donation_aggregate_amount: Option(Float),
    /// True for a memo entry; electronic-only (no box on the printed
    /// schedule). Column `memo_code`, `X` when true (field 21).
    memo: Bool,
    /// Column `memo_text_description` (field 22).
    memo_text: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// "SCHEDULE 13-B ITEMIZED REFUNDS OF DONATIONS": "for each refund of a
/// reported donation made by the committee, enter the payee's name and
/// address, the date the refund was made and the amount" (instructions dated
/// 10/2004)
/// ([fecfrm13.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13.pdf#page=3),
/// [fecfrm13i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13i.pdf#page=2)).
/// The `F133` record (FEC format workbook v8.4, sheet `F133`, "FORM 133 - FOR
/// EACH ITEMIZED REFUND OF DONATIONS"). Itemized refunds are added to those
/// itemized before and the sum goes on Line 6 of Form 13
/// ([fecfrm13i.pdf p2](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13i.pdf#page=2)).
/// Unlike `Form13Donation` there is no aggregate.
///
/// # Versions
///
/// v6.1–8.5 share the 21-field layout. v5.2–5.3 put the transaction ID and
/// back reference at the end and have no memo columns (FEC format workbook
/// v5.3, sheet `F133`). Paper layouts have no transaction ID, back reference
/// or entity type but carry an `image_number` (and a memo code from P3.2).
pub type Form13Refund {
  Form13Refund(
    /// The row type as filed, `F133`. Column `form_type` (FEC format
    /// workbook v8.4, sheet `F133`, field 1).
    form_type: String,
    /// The inaugural committee's FEC ID. Column `filer_committee_id_number`
    /// (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id_number` (field 3).
    transaction_id: Option(String),
    /// "Reference to the Tran ID of a Related Record". Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that record (sample `F132`). Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// Who was refunded: "Full Name (Last, First, Middle Initial) or Full
    /// Organization Name" and "Mailing Address", in the `contributor_*`
    /// columns ([fecfrm13.pdf p3](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm13.pdf#page=3)).
    /// Columns `entity_type`, `contributor_organization_name`,
    /// `contributor_last_name` … `contributor_suffix`, `contributor_street_1`
    /// … `contributor_zip` (fields 6–17).
    recipient: Entity,
    /// "Date Refund Made". Column `refund_date` (field 18).
    refund_date: Option(calendar.Date),
    /// "Amount of This Refund". Column `refund_amount` (field 19).
    refund_amount: Float,
    /// True for a memo entry; electronic-only. Column `memo_code`, `X` when
    /// true (field 20).
    memo: Bool,
    /// Column `memo_text_description` (field 21).
    memo_text: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
