//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::schedule_f`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address} as _
import libfec/itemization/common.{type CandidateRef, type Entity} as _

/// "SCHEDULE F - ITEMIZED COORDINATED EXPENDITURES MADE BY POLITICAL PARTY
/// COMMITTEES OR DESIGNATED AGENT(S) ON BEHALF OF CANDIDATES FOR FEDERAL
/// OFFICE": one expenditure a party committee (or its designated agent)
/// makes on behalf of a candidate in the general election under the special
/// limits of 52 U.S.C. § 30116(d). These "are not contributions to the
/// candidate and are not contributions in-kind reported on Schedule B", and
/// do not apply in primary elections
/// ([fecfrm3xi.pdf p23](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=23)).
/// Filed with Form 3X by party committees only
/// ([fecfrm3xi.pdf p8](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=8));
/// the total goes to Line 25 of the Detailed Summary Page (same page). The
/// row type is always `SF`, with no line number (FEC format workbook v8.4,
/// sheet `Sch F`, field 1).
///
/// A national committee may spend through designated agents (state or
/// subordinate party committees), and a state committee may designate
/// subordinate committees
/// ([fecfrm3xi.pdf p23–24](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=23)):
/// see `ScheduleF::filer_designated`, `ScheduleF::designating_committee`
/// and `ScheduleF::subordinate_committee`. Agents' expenditures reported
/// by the designating committee "should not be included in the reporting
/// committee's totals"
/// ([fecfrm3xi.pdf p24](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=24));
/// under the party guide's recommended method they are memo entries
/// ([partygui.pdf p130](https://www.fec.gov/resources/cms-content/documents/policy-guidance/partygui.pdf#page=130)).
///
/// # Versions
///
/// v8.0–8.5 have all 44 fields. v5.0–7.0 add `expenditure_purpose_code`,
/// and v5.0–6.3 `increased_limit`. v2–5.x have one combined `payee_name`
/// (and `payee_candidate_name`), split per `Entity::from_prefixed`, and a
/// conduit; v2 and v3 have no category code, v2 no memo or back-reference
/// columns. v1 gives the
/// designating committee's address instead of a subordinate committee and
/// has no entity type. Paper layouts have no transaction IDs, entity type or
/// committee IDs but carry an `image_number`.
pub type ScheduleF {
  ScheduleF(
    /// The row type as filed, `SF`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `Sch F`, field 1).
    form_type: String,
    /// The filing committee's FEC ID. Column `filer_committee_id_number`
    /// (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, unique for the life of the
    /// report; electronic-only. Column `transaction_id_number` (field 3).
    transaction_id: Option(String),
    /// The `transaction_id` of a related record. Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that related record. Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// "Has your committee been designated to make coordinated
    /// expenditures?": `Y` is `Some(true)`, `N` `Some(false)`, blank or any
    /// other value `None`. Column `coordinated_expenditures` (field 6,
    /// allowed values `Y,N`).
    filer_designated: Option(Bool),
    /// The committee that designated the filer ("If YES, name the
    /// designating committee"). Columns `designating_committee_id_number`
    /// (field 7, electronic-only), `designating_committee_name` (field 8);
    /// v1 also `designating_street_1` … `designating_zip_code`.
    designating_committee: ScheduleFCommittee,
    /// The subordinate committee, with its mailing address. Columns
    /// `subordinate_committee_id_number` (field 9, electronic-only),
    /// `subordinate_committee_name` (field 10), `subordinate_street_1` …
    /// `subordinate_zip_code` (fields 11–15). Absent in v1.
    subordinate_committee: ScheduleFCommittee,
    /// Who was paid: entity type, organization or person, mailing address.
    /// Columns `entity_type`, `payee_organization_name`, `payee_last_name` …
    /// `payee_suffix`, `payee_street_1` … `payee_zip_code` (fields 16–27);
    /// v1–5.x `payee_name`.
    payee: Entity,
    /// Date of the expenditure. Column `expenditure_date` (field 28).
    expenditure_date: Option(calendar.Date),
    /// Amount of the expenditure. Column `expenditure_amount` (field 29).
    expenditure_amount: Float,
    /// The coordinated expenditures made on behalf of this candidate for the
    /// general election
    /// ([fecfrm3xi.pdf p23](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=23)).
    /// Column `aggregate_general_elec_expended` (field 30).
    aggregate_general_election_expended: Option(Float),
    /// A coded purpose, v5.x–7.0 only (dropped in v8.0). Column
    /// `expenditure_purpose_code`.
    expenditure_purpose_code: Option(String),
    /// Purpose of the expenditure; required when the aggregate is over $0.00
    /// (field 31). Column `expenditure_purpose_descrip`.
    expenditure_purpose_description: Option(String),
    /// Category of disbursement, `001`–`012` per the workbook (field 32);
    /// the Schedule F instructions print only 001–007 and 011
    /// ([fecfrm3xi.pdf p23](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=23)).
    /// Kept raw: which source's meanings apply is an open question (fec-docs
    /// `wiki/Open-Questions.md`). Column `category_code`.
    category_code: Option(String),
    /// FEC ID of the payee, when it is a committee (entity `CCM`, `COM`,
    /// `PAC`, `PTY`). Column `payee_committee_id_number` (field 33).
    payee_committee_fec_id: Option(String),
    /// The federal candidate the expenditure supports ("Name of Federal
    /// Candidate Supported", "Office Sought", "State", "District"). Columns
    /// `payee_candidate_id_number` (field 34, electronic-only),
    /// `payee_candidate_last_name` … `payee_candidate_district` (fields
    /// 35–42); v1–5.x `payee_candidate_name`.
    candidate: CandidateRef,
    /// The conduit, v2–5.x only (dropped in v6.1). Column `conduit_name`.
    /// Its role is not in the sources read for this crate.
    conduit_name: Option(String),
    /// Columns `conduit_street_1` … `conduit_zip_code`, v2–5.x only.
    conduit_address: Address,
    /// True for a memo entry, not counted in the Line 25 total; agents'
    /// expenditures reported by the designating committee are memo entries
    /// ([partygui.pdf p130](https://www.fec.gov/resources/cms-content/documents/policy-guidance/partygui.pdf#page=130)).
    /// Column `memo_code`, `X` when true (field 43).
    memo: Bool,
    /// Column `memo_text_description` (field 44).
    memo_text: Option(String),
    /// Column `increased_limit`, raw: v5.0–6.3 and paper layouts P1–P2.4
    /// only. Its meaning and values are not in the sources read for this
    /// crate.
    increased_limit: Option(String),
    /// Column `24_hour_notice`, raw: paper layouts P1–P2.4 only. Its
    /// meaning and values are not in the sources read for this crate.
    notice_24_hour: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}

/// A committee named on Schedule F's designation block: the designating
/// committee or the subordinate committee (FEC format workbook v8.4, sheet
/// `Sch F`, fields 7–15).
pub type ScheduleFCommittee {
  ScheduleFCommittee(
    /// The committee's FEC ID; electronic-only.
    fec_id: Option(String),
    name: Option(String),
    /// Given for the subordinate committee (v2+) and, in v1 only, the
    /// designating committee; empty otherwise.
    address: Address,
  )
}
