//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::schedule_h3`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar

/// "SCHEDULE H3 - TRANSFERS FROM NONFEDERAL ACCOUNTS": one line of a
/// transfer from a committee's nonfederal account into its federal (or
/// allocation) account to pay the nonfederal share of allocated expenses
/// ([fecfrm3xi.pdf p28](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=28)).
/// Supports only Form 3X Line 18(a); Levin fund transfers are on Schedule H5
/// instead (same page).
///
/// On paper one transfer is one block broken down on lines i)–vi);
/// electronically **each breakdown line is its own row**, typed by
/// `event_type`. One `AD` row is required per transfer and every row's
/// `back_reference_transaction_id` points to it; `account_name`,
/// `receipt_date` and `total_amount_transferred` repeat on every row of the
/// transfer, while `transferred_amount` is the row's own breakdown amount
/// (FEC format workbook v8.4, sheet `Sch H3`, fields 4–10). Sum
/// `transferred_amount`, not `total_amount_transferred`.
///
/// # Versions
///
/// v6.1–8.5 have all 10 fields. v3–5.x have the same fields in another order
/// (transaction ID last). v1–2 and paper layouts have no breakdown rows (v1
/// lists events in columns of one row) and are read only for the transfer
/// itself; paper layouts have no transaction IDs but an `image_number`.
pub type ScheduleH3 {
  ScheduleH3(
    /// The row type as filed, `H3`. Column `form_type` (FEC format workbook
    /// v8.4, sheet `Sch H3`, field 1).
    form_type: String,
    /// The filing committee's FEC ID. Column `filer_committee_id_number`
    /// (field 2).
    filer_committee_id: String,
    /// The filer's ID for this row, unique for the life of the report;
    /// electronic-only. Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// The `transaction_id` of the transfer's `AD` row (on the `AD` row
    /// itself, usually its own ID). Column `back_reference_tran_id_number`
    /// (field 4).
    back_reference_transaction_id: Option(String),
    /// "Name of Account": the nonfederal account the money came from.
    /// Repeated on every row of the transfer. Column `account_name`
    /// (field 5).
    account_name: Option(String),
    /// What this row's amount pays for: `AD`, `GV`, `EA`, `DF`, `DC` or `PC`
    /// (see `ScheduleH3::event_type_label`). Column `event_type` (field 6).
    event_type: Option(String),
    /// For `DF` and `DC` rows, the Schedule H2 activity or event identifier.
    /// Column `event_activity_name` (field 7).
    event_activity_name: Option(String),
    /// Date of receipt of the transfer, repeated on every row. Column
    /// `receipt_date` (field 8).
    receipt_date: Option(calendar.Date),
    /// The whole transfer, repeated on every row of it, so summing it over
    /// rows overstates the transfer. Column `total_amount_transferred`
    /// (field 9).
    total_amount_transferred: Option(Float),
    /// This row's breakdown amount (FEC format workbook v8.4, sheet
    /// `Sch H3`, field 10, "Breakdown Amt for Items: i, ii, iii, iv)a), …").
    /// Column `transferred_amount`; absent in v1–2.
    transferred_amount: Float,
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
