//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations::schedule_a`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import gleam/option.{type Option}
import gleam/time/calendar
import libfec/cover/common.{type Address} as _
import libfec/itemization/common.{type CandidateRef, type Entity} as _

/// "SCHEDULE A - ITEMIZED RECEIPTS": one receipt a committee itemizes, with
/// the source, the date and amount, and the source's aggregate to date
/// ([fecfrm3i.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=6),
/// [fecfrm3xi.pdf p10](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=10)).
/// Filed with Forms 3, 3X, 3P and 4 (FEC format workbook v8.4, sheet `Sch A`,
/// field 1); Form 3L's `SA3L` lobbyist-bundling rows are a different layout
/// and not read as a `ScheduleA`.
///
/// The summary-page line the receipt supports is carried in the row type:
/// `SA11AI` is line 11(a)(i) (see `fec_parser::itemizations::line_number`).
/// A committee itemizes a person's receipts once they aggregate over $200 in
/// the election cycle (Forms 3, 3P) or calendar year (Form 3X)
/// ([fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4),
/// [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)),
/// so summing a filing's Schedule A rows does not give its total receipts.
///
/// # Versions
///
/// v8.0–8.5 have all 45 fields. v6.x–7.0 add `contribution_purpose_code`.
/// v3–5.x have one combined `contributor_name` (and `donor_candidate_name`),
/// split per `Entity::from_prefixed`. Paper layouts have no transaction IDs
/// or entity type but carry an `image_number`.
pub type ScheduleA {
  ScheduleA(
    /// The row type as filed, `SA` plus the line number: `SA11AI`. Column
    /// `form_type` (FEC format workbook v8.4, sheet `Sch A`, field 1).
    form_type: String,
    /// The filing committee's FEC ID. Column `filer_committee_id_number`
    /// (field 2).
    filer_committee_id: String,
    /// The filer's ID for this transaction, required and electronic-only.
    /// Column `transaction_id` (field 3).
    transaction_id: Option(String),
    /// The `transaction_id` of the record this one is a memo or child of
    /// (an earmark's conduit, a partnership's attribution, …). Column
    /// `back_reference_tran_id_number` (field 4).
    back_reference_transaction_id: Option(String),
    /// The schedule of that parent record (`SA11AI`, `SB23`, …). Column
    /// `back_reference_sched_name` (field 5).
    back_reference_schedule_name: Option(String),
    /// Who gave: entity type, organization or person, mailing address.
    /// Columns `entity_type`, `contributor_organization_name`,
    /// `contributor_last_name` … `contributor_suffix`, `contributor_street_1`
    /// … `contributor_zip_code` (fields 6–17); v3–5.x `contributor_name`.
    contributor: Entity,
    /// The election the receipt is for: a letter and a year, `P2024`
    /// (see `ScheduleA::election_code_label`). On Form 3X used only for
    /// refunds and loan repayments from federal candidates
    /// ([fecfrm3xi.pdf p10](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=10)).
    /// Column `election_code` (field 18).
    election_code: Option(String),
    /// Required when `election_code` is `O…` (Other). Column
    /// `election_other_description` (field 19).
    election_other_description: Option(String),
    /// Date of receipt. Column `contribution_date` (field 20).
    contribution_date: Option(calendar.Date),
    /// "Amount of Each Receipt this Period"; negative for a returned or
    /// bounced receipt itemized again
    /// ([fecfrm3i.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=7)).
    /// Column `contribution_amount` (field 21).
    contribution_amount: Float,
    /// The source's aggregate: cycle-to-date on Forms 3 and 3P, year-to-date
    /// on Form 3X (FEC format workbook v8.4, sheet `Sch A`, field 22, "F3 |
    /// F3P - Cycle to Date; F3X - YTD"). Column `contribution_aggregate`.
    contribution_aggregate: Option(Float),
    /// A coded purpose, v5.x–7.0 only (dropped in v8.0). Column
    /// `contribution_purpose_code`.
    contribution_purpose_code: Option(String),
    /// Free-text description of the receipt (earmarks, in-kind items, …).
    /// Column `contribution_purpose_descrip` (field 23).
    contribution_purpose_description: Option(String),
    /// For individuals; required once the aggregate is over $200 (FEC
    /// format workbook v8.4, sheet `Sch A`, fields 24–25). Column
    /// `contributor_employer` (field 24).
    contributor_employer: Option(String),
    /// Column `contributor_occupation` (field 25).
    contributor_occupation: Option(String),
    /// FEC ID of a contributing committee (entity `CCM`, `PAC`, `PTY`).
    /// Column `donor_committee_fec_id` (field 26).
    donor_committee_fec_id: Option(String),
    /// Column `donor_committee_name` (field 27).
    donor_committee_name: Option(String),
    /// A contributing candidate (entity `CAN`, `CCM`). Columns
    /// `donor_candidate_fec_id`, `donor_candidate_last_name` …
    /// `donor_candidate_district` (fields 28–36).
    donor_candidate: CandidateRef,
    /// The conduit an earmarked contribution came through (ActBlue,
    /// WinRed, …). Column `conduit_name` (field 37).
    conduit_name: Option(String),
    /// Columns `conduit_street1` … `conduit_zip_code` (fields 38–42).
    conduit_address: Address,
    /// True for a memo entry, which does not count toward the schedule's or
    /// summary page's totals
    /// ([partygui.pdf p213](https://www.fec.gov/resources/cms-content/documents/policy-guidance/partygui.pdf#page=213)).
    /// Column `memo_code`, `X` when true (field 43).
    memo: Bool,
    /// Column `memo_text_description` (field 44).
    memo_text: Option(String),
    /// A Schedule I or L system code tying the receipt to an account.
    /// Column `reference_code` (field 45).
    reference_code: Option(String),
    /// The scanned page of a paper filing. Column `image_number` (paper
    /// layouts only).
    image_number: Option(String),
  )
}
