[project]
name = "libfec-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Garcia", email = "alexsebastian.garcia@gmail.com" }
]
requires-python = ">=3.7"
dependencies = []

[project.scripts]
libfec-parser = "libfec_parser:main"

[tool.maturin]
module-name = "libfec_parser"
python-packages = ["libfec_parser"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
