[package]
name = "fec-cli"
version = "0.0.31"
edition = "2021"
authors = ["Alex Garcia <alexsebastian.garcia@gmail.com>"]
description = "A fast FEC filing parser and toolkit"
repository = "https://github.com/asg017/libfec"
homepage = "https://github.com/asg017/libfec"

[package.metadata.wix]
upgrade-guid = "BA74C7A9-7590-48BD-B8B4-E502C5DD79B6"
path-guid = "EC65EB40-397C-4215-A391-CD42F22B75C9"
license = false
eula = false


[[bin]]
name = "libfec"
path = "src/main.rs"

[dependencies]
fec-parser = { path = "../fec-parser" }
fec-api = { path = "../fec-api" }
clap = { version = "4.5.60", features = ["derive", "cargo", "env"] }
anyhow = {version="1.0", features=["backtrace"]}
csv = "1.2.2"
colored = "2.1.0"
rusqlite = { version = "0.34", features = ["bundled", "jiff"] }
thiserror = "1.0.63"
indicatif = "0.17.8"
tabled = "0.20.0"
ureq = "3.0.10"
quick-xml = "=0.36.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
uuid = { version = "1.11", features = ["v4"] }
zip = "4.2.0"
url = "2.5.2"
jiff = "0.2.5"
rust_xlsxwriter = "0.89.0"
num-format = "0.4.4"
derive_builder = "0.20.2"
sha2 = "0.10"
tempfile = "3.20.0"
etcetera = "0.10.0"
ratatui = "0.30"
crossterm = "0.28"
arboard = "3.6.1"
xmlparser = "0.13"
open = "5"
time = "0.3.46"
indexmap = "2"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[dev-dependencies]
insta = { version = "1.45.0", features = ["yaml"] }
#rusqlite = {version="0.32.1", features = ["bundled"] }