//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::covers`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import libfec/cover/form1
import libfec/cover/form13
import libfec/cover/form1m
import libfec/cover/form2
import libfec/cover/form24
import libfec/cover/form3
import libfec/cover/form3l
import libfec/cover/form3p
import libfec/cover/form3x
import libfec/cover/form4
import libfec/cover/form5
import libfec/cover/form6
import libfec/cover/form7
import libfec/cover/form9
import libfec/cover/form99

/// A typed cover record. See each variant's struct for field documentation.
pub type Cover {
  Form1(form1.Form1)
  Form3(form3.Form3)
  Form3P(form3p.Form3P)
  Form1M(form1m.Form1M)
  Form3X(form3x.Form3X)
  Form3L(form3l.Form3L)
  Form4(form4.Form4)
  Form7(form7.Form7)
  Form13(form13.Form13)
  Form24(form24.Form24)
  Form5(form5.Form5)
  Form6(form6.Form6)
  Form9(form9.Form9)
  Form2(form2.Form2)
  Form99(form99.Form99)
}
