//// Generated by crates/fec-gleam/src/bin/gen.rs. Do not edit.
////
//// Typed records from the Rust module `fec_parser::itemizations`.
////
//// Each record's fields are in the Rust struct's order: that order is
//// the contract with the Erlang tuple the NIF builds.

import libfec/itemization/form13_items
import libfec/itemization/form5_items
import libfec/itemization/form6_items
import libfec/itemization/form7_items
import libfec/itemization/form9_items
import libfec/itemization/schedule_a
import libfec/itemization/schedule_a3l
import libfec/itemization/schedule_b
import libfec/itemization/schedule_c
import libfec/itemization/schedule_c1
import libfec/itemization/schedule_c2
import libfec/itemization/schedule_d
import libfec/itemization/schedule_e
import libfec/itemization/schedule_f
import libfec/itemization/schedule_h1
import libfec/itemization/schedule_h2
import libfec/itemization/schedule_h3
import libfec/itemization/schedule_h4
import libfec/itemization/schedule_h5
import libfec/itemization/schedule_h6
import libfec/itemization/schedule_l
import libfec/itemization/text

/// One typed itemization record. `None` from `Itemization::from_record`
/// means the row is not an itemization (the cover, `F3PS`, …) or its record
/// type has no struct yet.
///
/// Serialized with its `record_family` as a `"family"` tag (`"SA"`), then
/// the struct's fields.
pub type Itemization {
  ScheduleA(schedule_a.ScheduleA)
  ScheduleB(schedule_b.ScheduleB)
  ScheduleD(schedule_d.ScheduleD)
  ScheduleF(schedule_f.ScheduleF)
  ScheduleH1(schedule_h1.ScheduleH1)
  ScheduleH2(schedule_h2.ScheduleH2)
  ScheduleH3(schedule_h3.ScheduleH3)
  ScheduleH4(schedule_h4.ScheduleH4)
  ScheduleH5(schedule_h5.ScheduleH5)
  ScheduleH6(schedule_h6.ScheduleH6)
  Form5Contribution(form5_items.Form5Contribution)
  Form5Expenditure(form5_items.Form5Expenditure)
  Form6Contribution(form6_items.Form6Contribution)
  Form7Communication(form7_items.Form7Communication)
  Form9ControllingPerson(form9_items.Form9ControllingPerson)
  Form9Donation(form9_items.Form9Donation)
  Form9Disbursement(form9_items.Form9Disbursement)
  Form9Candidate(form9_items.Form9Candidate)
  Form13Donation(form13_items.Form13Donation)
  Form13Refund(form13_items.Form13Refund)
  ScheduleL(schedule_l.ScheduleL)
  Text(text.TextRecord)
  ScheduleA3L(schedule_a3l.ScheduleA3L)
  ScheduleE(schedule_e.ScheduleE)
  ScheduleC(schedule_c.ScheduleC)
  ScheduleC1(schedule_c1.ScheduleC1)
  ScheduleC2(schedule_c2.ScheduleC2)
}
