// `make gen-types`, step 2 of 2: turn the ts-rs export and label tables written
// by `src/bin/gen-types.rs` (step 1) into the committed js/generated/.
//
//   node scripts/gen-types.mjs <scratch-dir>
//
// - Every file gets our header in place of ts-rs's.
// - Rustdoc intra-doc links become TypeDoc links ({@link ScheduleA},
//   {@link ScheduleA.memo}, {@link entityTypeLabel}) or, for anything with no JS
//   counterpart (Rust methods, crate functions), plain code spans.
// - The two unions are re-tagged for JS: Itemization's serde `family` tag and
//   Cover's `{ form, data }` both become a `type` field holding the struct
//   name (`{ type: "ScheduleA" } & ScheduleA`). The token decoder (js/tokens.ts)
//   produces exactly that shape; Rust's serde output is unchanged.
// - labels.ts: one function per public Rust label function, from its table.
// - keys.json: every struct's keys in serde order (decoder tests).
// - index.ts: re-exports, plus ITEMIZATION_TYPES and COVER_TYPES.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const HEADER = "// Generated by scripts/gen-types.mjs from fec-parser (via ts-rs). Do not edit.";
const scratch = process.argv[2];
if (!scratch) {
  console.error("usage: node scripts/gen-types.mjs <scratch-dir>");
  process.exit(2);
}
const outDir = new URL("../js/generated/", import.meta.url);
const parserSrc = new URL("../../fec-parser/src/", import.meta.url);

const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

// ---- read the ts-rs export ----------------------------------------------------

const files = new Map(); // type name -> source
for (const f of readdirSync(scratch).sort()) {
  if (f.endsWith(".ts")) files.set(f.slice(0, -3), readFileSync(join(scratch, f), "utf8"));
}

/** Field names of an object type, in declaration (= serde) order. */
function fieldsOf(src) {
  const body = src.slice(src.indexOf("export type"));
  const noComments = body.replace(/\/\*\*[\s\S]*?\*\//g, "");
  const open = noComments.indexOf("{");
  if (open < 0 || /=\s*{\s*"/.test(noComments)) return null; // a union, not a struct
  return [...noComments.slice(open).matchAll(/(?:^|[{,])\s*(\w+): /gm)].map((m) => m[1]);
}

const fields = new Map();
for (const [name, src] of files) {
  const f = fieldsOf(src);
  if (f) fields.set(name, f);
}

const labels = JSON.parse(readFileSync(join(scratch, "labels.json"), "utf8")).map((l) => {
  const rustName = l.rust.split("::").pop();
  return { ...l, rustName, jsName: camel(rustName) };
});
const labelByRust = new Map(labels.map((l) => [l.rustName, l]));

// ---- intra-doc links ------------------------------------------------------------

/** `current`: the type whose docs these are (resolves `Self::x`). */
function rewriteLinks(text, current) {
  // [`shown`](Self::path) and [`path`]
  return text
    .replace(/\[`([^`\]]+)`\]\(([^)\s]+)\)/g, (_, shown, target) => link(target, shown, current))
    .replace(/\[`([^`\]]+)`\](?!\()/g, (_, target) => link(target, null, current));
}

function link(target, shown, current) {
  const segs = target
    .replace(/\(\)$/, "")
    .split("::")
    .filter((s) => !["crate", "covers", "itemizations", "fec_parser"].includes(s))
    .map((s) => (s === "Self" ? current : s));
  const [a, b] = segs.length === 1 ? [segs[0], null] : segs.slice(-2);
  if (b === null) {
    if (fields.has(a) || a === "Itemization" || a === "Cover") return `{@link ${a}}`;
    if (labelByRust.has(a)) return `{@link ${labelByRust.get(a).jsName}}`;
    if (fields.get(current)?.includes(a)) return `{@link ${current}.${a} | ${a}}`;
    return "`" + (shown ?? a) + "`";
  }
  if (fields.get(a)?.includes(b)) {
    return shown ? `{@link ${a}.${b} | ${shown}}` : `{@link ${a}.${b}}`;
  }
  // `X::y_label` methods with a JS label function of the same name.
  if (labelByRust.has(b)) return `{@link ${labelByRust.get(b).jsName}}`;
  return "`" + (shown ?? `${a}::${b}`) + "`";
}

// ---- unions ---------------------------------------------------------------------

function retagUnion(name, src, armRe, render) {
  const decl = src.match(new RegExp(`export type ${name} = (.*);\\s*$`, "m"));
  if (!decl) throw new Error(`${name}.ts: no union declaration`);
  const arms = decl[1].split(" | ").map((arm) => {
    const m = arm.match(armRe);
    if (!m) throw new Error(`${name}.ts: unexpected union arm ${arm}`);
    return m[1];
  });
  const union =
    `export type ${name} =\n` + arms.map((t) => `  | ({ type: "${t}" } & ${t})`).join("\n") + ";";
  return { arms, src: src.replace(decl[0], render(union, arms)) };
}

const itemization = retagUnion(
  "Itemization",
  files.get("Itemization"),
  /^\{ "family": "[^"]+" \} & (\w+)$/,
  (union) => union,
);
files.set("Itemization", itemization.src);
const cover = retagUnion(
  "Cover",
  files.get("Cover"),
  /^\{ "form": "(\w+)", "data": (?:\w+) \}$/,
  (union) => union,
);
files.set("Cover", cover.src);
for (const t of [...itemization.arms, ...cover.arms]) {
  if (!fields.has(t)) throw new Error(`union arm ${t} has no exported struct`);
}

// ---- docs on the unions ----------------------------------------------------------

const UNION_DOCS = {
  Itemization: `/**
 * One typed itemization record: a {@link ScheduleA} receipt, a
 * {@link ScheduleB} disbursement, … . Narrow it with a \`switch\` on \`type\`,
 * which is the struct's name:
 *
 * \`\`\`ts
 * switch (row.itemization.type) {
 *   case "ScheduleA": row.itemization.contribution_amount; break;
 *   case "ScheduleB": row.itemization.expenditure_amount; break;
 * }
 * \`\`\`
 *
 * Rust and \`libfec\`'s JSON output tag these with a \`family\` field (\`"SA"\`)
 * instead; the JS layer replaces it with \`type\`.
 */`,
  Cover: `/**
 * A filing's typed cover record: {@link Form3X}, {@link Form3}, … . Narrow it
 * with a \`switch\` on \`type\`, which is the struct's name:
 *
 * \`\`\`ts
 * switch (filing.cover?.type) {
 *   case "Form3X": filing.cover.summary.line6c_total_receipts.column_a; break;
 * }
 * \`\`\`
 *
 * Rust and \`libfec info -f json\` nest these as \`{ form, data }\`; the JS layer
 * flattens them to \`{ type, ...data }\`.
 */`,
};

// ---- write ----------------------------------------------------------------------

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const write = (name, text) => writeFileSync(new URL(name, outDir), text.trimEnd() + "\n");

for (const [name, src0] of files) {
  let src = src0.replace(/^\/\/ This file was generated by \[ts-rs\].*\n/, HEADER + "\n");
  if (name in UNION_DOCS) {
    src = src.replace(/\/\*\*[\s\S]*?\*\/\n(?=export type)/, "");
    src = src.replace(/export type/, UNION_DOCS[name] + "\nexport type");
  }
  src = rewriteLinks(src, name);
  if (/\[`/.test(src)) throw new Error(`${name}.ts: an intra-doc link survived`);
  write(`${name}.ts`, src);
}

// labels.ts
function rustDocs(fnName) {
  for (const sub of ["covers", "itemizations"]) {
    for (const f of readdirSync(new URL(`${sub}/`, parserSrc))) {
      const src = readFileSync(new URL(`${sub}/${f}`, parserSrc), "utf8");
      const m = src.match(new RegExp(`((?:^///.*\\n)+)pub fn ${fnName}\\(`, "m"));
      if (m) return m[1].split("\n").filter(Boolean).map((l) => l.replace(/^\/\/\/ ?/, ""));
    }
  }
  throw new Error(`no docs found for pub fn ${fnName}`);
}

const SHAPE_CODE = {
  exact: "code.trim().toUpperCase()",
  first_char: "code.trim().charAt(0).toUpperCase()",
  number: '/^\\d+$/.test(code.trim()) ? String(Number(code.trim())) : ""',
};

let labelsTs = `${HEADER}
// Tables tabulated from fec-parser's label functions by src/bin/gen-types.rs.

const lookup = (table: Readonly<Record<string, string>>, key: string): string | null =>
  Object.hasOwn(table, key) ? table[key]! : null;
`;
for (const l of labels) {
  const docs = rustDocs(l.rustName).map((d) => rewriteLinks(d, null));
  const table = `${l.jsName.toUpperCase()}_TABLE`;
  labelsTs += `
const ${table}: Readonly<Record<string, string>> = ${JSON.stringify(l.table, null, 2)};

/**
${docs.map((d) => ` * ${d}`.trimEnd()).join("\n")}
 *
 * Returns \`null\` for \`null\`, \`undefined\` and unknown codes. Mirrors Rust's
 * \`fec_parser::${l.rust}\`.
 */
export function ${l.jsName}(code: string | null | undefined): string | null {
  if (code == null) return null;
  return lookup(${table}, ${SHAPE_CODE[l.shape]});
}
`;
}
write("labels.ts", rewriteLinks(labelsTs, null));

// keys.json
write(
  "keys.json",
  JSON.stringify(Object.fromEntries([...fields].sort(([a], [b]) => a.localeCompare(b))), null, 2),
);

// index.ts
const types = [...files.keys()].sort();
write(
  "index.ts",
  `${HEADER}
${types.map((t) => `export type { ${t} } from "./${t}.js";`).join("\n")}
export { ${labels.map((l) => l.jsName).join(", ")} } from "./labels.js";

/** Every {@link Itemization} \`type\`, in Rust's declaration order. */
export const ITEMIZATION_TYPES = ${JSON.stringify(itemization.arms)} as const;

/** Every {@link Cover} \`type\`, in Rust's declaration order. */
export const COVER_TYPES = ${JSON.stringify(cover.arms)} as const;

import type { Itemization } from "./Itemization.js";
import type { Cover } from "./Cover.js";
`,
);
console.log(`gen-types: ${types.length} types, ${labels.length} label functions`);
