"""Type stubs for :mod:`libfec.itemizations`.

Generated by ``crates/fec-py/scripts/gen_cover_stubs.py`` from
``crates/fec-parser/src/itemizations/*.rs`` -- do not edit by hand.
"""

from datetime import date
from typing import Any, TypeAlias, final
from .covers import Address, PersonName

__all__ = [
    "Itemization",
    "Entity",
    "CandidateRef",
    "ScheduleA",
]

Itemization: TypeAlias = (
    ScheduleA
)

@final
class Entity:
    """The other party to an itemized transaction: a contributor, payee, lender
    or creditor. The FEC format gives each one an `entity_type` code, an
    organization name (required unless the entity is an individual or a
    candidate) and a person's name (required for those two), and an address
    (e.g. FEC format workbook v8.4, sheet `Sch A`, fields 6–17)."""
    @property
    def entity_type(self) -> str | None:
        """`IND`, `ORG`, `COM`, … — see [`Entity::entity_type_label`]. Absent
        before v5.0 and on paper filings."""
    @property
    def organization_name(self) -> str | None:
        """The organization's name, for anything but a person."""
    @property
    def name(self) -> PersonName:
        """The person's name, for an individual or a candidate."""
    @property
    def address(self) -> Address:
        ...
    def is_individual(self) -> bool:
        """True for an individual (`IND`) or a candidate (`CAN`), the entity
        types identified by a person's name."""
    def display_name(self) -> str:
        """The name to show: the person's for individuals and candidates, else
        the organization's (falling back to whichever is present)."""
    def entity_type_label(self) -> str | None:
        """See [`entity_type_label`]."""
    def to_dict(self) -> dict[str, Any]:
        """The fields as a `dict`, nested covers as nested dicts."""
    def __eq__(self, other: object, /) -> bool: ...

@final
class CandidateRef:
    """A federal candidate an itemization names: the donor candidate of a
    receipt, the beneficiary of a disbursement, the candidate an independent
    expenditure supports or opposes. Office is `H`, `S` or `P`; state and
    district identify the seat (e.g. FEC format workbook v8.4, sheet `Sch A`,
    fields 28–36)."""
    @property
    def fec_id(self) -> str | None:
        """The candidate's FEC ID (`H0VA01234`)."""
    @property
    def name(self) -> PersonName:
        ...
    @property
    def office(self) -> str | None:
        """`H` House, `S` Senate, `P` President; see [`CandidateRef::office_label`]."""
    @property
    def state(self) -> str | None:
        ...
    @property
    def district(self) -> str | None:
        ...
    def is_empty(self) -> bool:
        """True when no part of the reference is filled in."""
    def office_label(self) -> str | None:
        """"House", "Senate" or "President"; see [`crate::covers::office_label`]."""
    def to_dict(self) -> dict[str, Any]:
        """The fields as a `dict`, nested covers as nested dicts."""
    def __eq__(self, other: object, /) -> bool: ...

@final
class ScheduleA:
    """"SCHEDULE A - ITEMIZED RECEIPTS": one receipt a committee itemizes, with
    the source, the date and amount, and the source's aggregate to date
    ([fecfrm3i.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=6),
    [fecfrm3xi.pdf p10](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=10)).
    Filed with Forms 3, 3X, 3P and 4 (FEC format workbook v8.4, sheet `Sch A`,
    field 1); Form 3L's `SA3L` lobbyist-bundling rows are a different layout
    and not read as a `ScheduleA`.

    The summary-page line the receipt supports is carried in the row type:
    `SA11AI` is line 11(a)(i) (see [`crate::itemizations::line_number`]).
    A committee itemizes a person's receipts once they aggregate over $200 in
    the election cycle (Forms 3, 3P) or calendar year (Form 3X)
    ([fecfrm3i.pdf p4](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=4),
    [fecfrm3xi.pdf p6](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=6)),
    so summing a filing's Schedule A rows does not give its total receipts.

    # Versions

    v8.0–8.5 have all 45 fields. v6.x–7.0 add `contribution_purpose_code`.
    v3–5.x have one combined `contributor_name` (and `donor_candidate_name`),
    split per [`Entity::from_prefixed`]. Paper layouts have no transaction IDs
    or entity type but carry an `image_number`."""
    @property
    def form_type(self) -> str:
        """The row type as filed, `SA` plus the line number: `SA11AI`. Column
        `form_type` (FEC format workbook v8.4, sheet `Sch A`, field 1)."""
    @property
    def filer_committee_id(self) -> str:
        """The filing committee's FEC ID. Column `filer_committee_id_number`
        (field 2)."""
    @property
    def transaction_id(self) -> str | None:
        """The filer's ID for this transaction, required and electronic-only.
        Column `transaction_id` (field 3)."""
    @property
    def back_reference_transaction_id(self) -> str | None:
        """The `transaction_id` of the record this one is a memo or child of
        (an earmark's conduit, a partnership's attribution, …). Column
        `back_reference_tran_id_number` (field 4)."""
    @property
    def back_reference_schedule_name(self) -> str | None:
        """The schedule of that parent record (`SA11AI`, `SB23`, …). Column
        `back_reference_sched_name` (field 5)."""
    @property
    def contributor(self) -> Entity:
        """Who gave: entity type, organization or person, mailing address.
        Columns `entity_type`, `contributor_organization_name`,
        `contributor_last_name` … `contributor_suffix`, `contributor_street_1`
        … `contributor_zip_code` (fields 6–17); v3–5.x `contributor_name`."""
    @property
    def election_code(self) -> str | None:
        """The election the receipt is for: a letter and a year, `P2024`
        (see [`ScheduleA::election_code_label`]). On Form 3X used only for
        refunds and loan repayments from federal candidates
        ([fecfrm3xi.pdf p10](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3xi.pdf#page=10)).
        Column `election_code` (field 18)."""
    @property
    def election_other_description(self) -> str | None:
        """Required when `election_code` is `O…` (Other). Column
        `election_other_description` (field 19)."""
    @property
    def contribution_date(self) -> date | None:
        """Date of receipt. Column `contribution_date` (field 20)."""
    @property
    def contribution_amount(self) -> float:
        """"Amount of Each Receipt this Period"; negative for a returned or
        bounced receipt itemized again
        ([fecfrm3i.pdf p7](https://www.fec.gov/resources/cms-content/documents/policy-guidance/fecfrm3i.pdf#page=7)).
        Column `contribution_amount` (field 21)."""
    @property
    def contribution_aggregate(self) -> float | None:
        """The source's aggregate: cycle-to-date on Forms 3 and 3P, year-to-date
        on Form 3X (FEC format workbook v8.4, sheet `Sch A`, field 22, "F3 |
        F3P - Cycle to Date; F3X - YTD"). Column `contribution_aggregate`."""
    @property
    def contribution_purpose_code(self) -> str | None:
        """A coded purpose, v5.x–7.0 only (dropped in v8.0). Column
        `contribution_purpose_code`."""
    @property
    def contribution_purpose_description(self) -> str | None:
        """Free-text description of the receipt (earmarks, in-kind items, …).
        Column `contribution_purpose_descrip` (field 23)."""
    @property
    def contributor_employer(self) -> str | None:
        """For individuals; required once the aggregate is over $200 (FEC
        format workbook v8.4, sheet `Sch A`, fields 24–25). Column
        `contributor_employer` (field 24)."""
    @property
    def contributor_occupation(self) -> str | None:
        """Column `contributor_occupation` (field 25)."""
    @property
    def donor_committee_fec_id(self) -> str | None:
        """FEC ID of a contributing committee (entity `CCM`, `PAC`, `PTY`).
        Column `donor_committee_fec_id` (field 26)."""
    @property
    def donor_committee_name(self) -> str | None:
        """Column `donor_committee_name` (field 27)."""
    @property
    def donor_candidate(self) -> CandidateRef:
        """A contributing candidate (entity `CAN`, `CCM`). Columns
        `donor_candidate_fec_id`, `donor_candidate_last_name` …
        `donor_candidate_district` (fields 28–36)."""
    @property
    def conduit_name(self) -> str | None:
        """The conduit an earmarked contribution came through (ActBlue,
        WinRed, …). Column `conduit_name` (field 37)."""
    @property
    def conduit_address(self) -> Address:
        """Columns `conduit_street1` … `conduit_zip_code` (fields 38–42)."""
    @property
    def memo(self) -> bool:
        """True for a memo entry, which does not count toward the schedule's or
        summary page's totals
        ([partygui.pdf p213](https://www.fec.gov/resources/cms-content/documents/policy-guidance/partygui.pdf#page=213)).
        Column `memo_code`, `X` when true (field 43)."""
    @property
    def memo_text(self) -> str | None:
        """Column `memo_text_description` (field 44)."""
    @property
    def reference_code(self) -> str | None:
        """A Schedule I or L system code tying the receipt to an account.
        Column `reference_code` (field 45)."""
    @property
    def image_number(self) -> str | None:
        """The scanned page of a paper filing. Column `image_number` (paper
        layouts only)."""
    def election_code_label(self) -> str | None:
        """"Primary", "General", … for `election_code`; see
        [`crate::covers::election_code_label`]."""
    def line_number(self) -> str | None:
        """The summary-page line, `11AI`; see [`crate::itemizations::line_number`]."""
    def to_dict(self) -> dict[str, Any]:
        """The fields as a `dict`, nested covers as nested dicts."""
    def __eq__(self, other: object, /) -> bool: ...
