import datetime
from collections.abc import Iterable, Iterator
from typing import Any, final

@final
class Item:
    @property
    def title(self) -> str: ...
    @property
    def link(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def pub_date(self) -> datetime.datetime | None: ...
    @property
    def guid(self) -> str: ...
    @property
    def committee_id(self) -> str | None: ...
    @property
    def filing_id(self) -> str | None: ...
    @property
    def form_type(self) -> str | None: ...
    @property
    def coverage_from(self) -> datetime.date | None: ...
    @property
    def coverage_through(self) -> datetime.date | None: ...
    @property
    def report_type(self) -> str | None: ...
    @property
    def committee_name(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

@final
class Feed:
    @property
    def title(self) -> str: ...
    @property
    def link(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def items(self) -> list[Item]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Item]: ...

def parse_feed(xml: str | bytes) -> Feed: ...
def feed_url(
    preset: str = "all",
    *,
    committees: str | Iterable[str] | None = None,
    forms: str | Iterable[str] | None = None,
    states: str | Iterable[str] | None = None,
    parties: str | Iterable[str] | None = None,
) -> str: ...
def fetch(
    preset: str = "all",
    *,
    committees: str | Iterable[str] | None = None,
    forms: str | Iterable[str] | None = None,
    states: str | Iterable[str] | None = None,
    parties: str | Iterable[str] | None = None,
    timeout: float = 60.0,
) -> Feed: ...

__all__ = ["Feed", "Item", "feed_url", "fetch", "parse_feed"]
