name: Deploy Site
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "site/**"
      - ".github/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: site/package-lock.json
      - run: npm ci
        working-directory: site/
      - run: npm run build
        working-directory: site/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site/.vitepress/dist
      - id: deployment
        uses: actions/deploy-pages@v4
