name: "test-wasm"
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: Build WASM package
        run: make build
        working-directory: crates/fec-wasm
      - name: Upload WASM package
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: crates/fec-wasm/pkg/
