name: "build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15-intel, ubuntu-22.04-arm, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -p fec-cli
  cross-compile-armv7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add armv7-unknown-linux-gnueabihf
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf
      - run: cargo build -p fec-cli --target armv7-unknown-linux-gnueabihf
        env:
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc